Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2019-10, with the labels that each got.

#177 [Bugfix]Change breadcrumb link "Aria-current" value from "page" to "location"
  src/core/Breadcrumb/BreadcrumbLink.tsx
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
Labels: bug

#167 Release 0.2.6
  package.json
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Link/Link.tsx
  src/core/Breadcrumb/BreadcrumbLink.tsx
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/Panel/__snapshots__/PanelExpansion.test.tsx.snap
  yarn.lock
Labels: release

#168 Create issue templates
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Question.md
  .github/ISSUE_TEMPLATE/Support.md
Labels: DX

#195 Bugfix/do not try to export suomifi theme function
  src/core/theme/index.ts
  src/index.tsx
Labels: bug

#169 Create PR template
  .github/pull_request_template.md
Labels: DX

#200 Add Text smallScreen to tests
  src/core/Text/Text.md
  src/core/Text/Text.test.tsx
  src/core/Text/__snapshots__/Text.test.tsx.snap
Labels: DX, Selected for Development, WIP, bug

#198 Replace any with correct interface
  src/core/theme/utils/typography.ts
Labels: DX, Selected for Development, WIP, bug

#207 Tests for tokens-prop
  src/components/Panel/PanelExpansionGroup.tsx
  src/core/Block/Block.baseStyles.ts
  src/core/Block/Block.tsx
  src/core/Breadcrumb/Breadcrumb.baseStyles.ts
  src/core/Breadcrumb/Breadcrumb.tsx
  src/core/Button/Button.baseStyles.tsx
  src/core/Button/Button.tsx
  src/core/Button/UnstyledButton.tsx
  src/core/Colors/Colors.baseStyles.tsx
  src/core/Colors/Colors.tsx
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/Dropdown.tsx
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/Toggle/Toggle.baseStyles.tsx
  src/core/Form/Toggle/Toggle.tsx
  src/core/Heading/Heading.baseStyles.ts
  src/core/Heading/Heading.tsx
  src/core/Link/Link.baseStyles.ts
  src/core/Link/Link.tsx
  src/core/Link/LinkExternal.tsx
  src/core/Menu/Menu.baseStyles.tsx
  src/core/Menu/Menu.tsx
  src/core/Panel/Panel.baseStyles.tsx
  src/core/Panel/Panel.tsx
  src/core/Panel/PanelExpansion.baseStyles.tsx
  src/core/Panel/PanelExpansion.tsx
  src/core/Panel/PanelExpansionGroup.baseStyles.tsx
  src/core/Panel/PanelExpansionGroup.tsx
  src/core/Paragraph/Paragraph.baseStyles.ts
  src/core/Paragraph/Paragraph.tsx
  src/core/Text/Text.baseStyles.ts
  src/core/Text/Text.tsx
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/core/theme/index.ts
  src/core/theme/tokens.test.tsx
  src/core/theme/utils/defaults.ts
  src/core/utils/index.ts
Labels: DX, WIP, bug

#205 [Refactor] Set button fullWidth using className
  src/core/Button/Button.baseStyles.tsx
  src/core/Button/Button.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
Labels: DX, WIP

#201 [Feature] index.ts for utils/css
  src/components/Panel/PanelExpansion.tsx
  src/core/Colors/Colors.tsx
  src/core/Link/Link.baseStyles.ts
  src/core/Panel/PanelExpansion.baseStyles.tsx
  src/core/theme/colors.ts
  src/core/theme/utils/typography.ts
  src/reset/HtmlA/HtmlA.tsx
  src/utils/css/index.ts
Labels: DX

#211 Bugfix/create token for wrong text sizes
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Menu/Menu.baseStyles.tsx
  src/core/Panel/__snapshots__/PanelExpansion.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/core/theme/reset/index.ts
  src/core/theme/typography.ts
Labels: Important, WIP, bug

#212 Bugfix/update documentation of styling based on design tokens implementation refactoring
  DEVELOPMENT.md
  src/core/Colors/Colors.baseStyles.tsx
  src/core/Colors/Colors.tsx
  src/core/Form/Toggle/Toggle.baseStyles.tsx
Labels: DX, Important, bug
