Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2019-11, with the labels that each got.

#223 Expansion panel alignment in IE and Edge
  src/core/Panel/PanelExpansionGroup.baseStyles.tsx
  src/core/theme/__snapshots__/tokens.test.tsx.snap
Labels: bug

#216 Panel expansion disabled attribute
  src/components/Panel/PanelExpansion.tsx
  src/core/Panel/__snapshots__/PanelExpansion.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
Labels: WIP, bug

#227 [Bugfix] Only allow placeholder for search input
  src/components/Form/SearchInput.tsx
  src/components/Form/TextInput.tsx
  src/core/Form/SearchInput/SearchInput.md
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.tsx
Labels: WIP, bug

#231 Add architecture diagram to DEVELOPMENT readme
  DEVELOPMENT.md
  suomifi-ui-components.png
Labels: DX, enhancement

#236 [Feature] Mouse cursor change for disabled Button
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/utils/css.ts
  src/core/Button/Button.baseStyles.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Panel/__snapshots__/PanelExpansion.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
Labels: Accessibility, enhancement

#235 Update dev readme
  DEVELOPMENT.md
  README.md
Labels: DX, enhancement

#243 [BreakingChange] Update suomifi-design-tokens to 0.3.0
  package.json
  src/core/theme/colors.ts
  src/core/theme/index.ts
  src/core/theme/spacing.ts
  src/core/theme/typography.ts
  src/core/theme/utils/colors.ts
  src/core/theme/utils/spacing.ts
  src/core/theme/utils/typography/fontsize.ts
  src/core/theme/utils/typography/typographyutil.ts
  yarn.lock
Labels: bug

#260 Add more codeowners
  .github/CODEOWNERS
Labels: DX

#252 [Feature] Icon component custom props
  package.json
  src/components/Svg/Svg.tsx
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Icon/Icon.tsx
  src/core/Icon/__snapshots__/Icon.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/Panel/__snapshots__/PanelExpansion.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  yarn.lock
Labels: enhancement

#264 Change pattern to modules in styleguidist headings and filenames
  .styleguidist/modules.md
  .styleguidist/styleguidist.sections.js
Labels: bug

#263 [BreakingChange]Remove heading 6 variant
  .styleguidist/typography.md
  package.json
  src/core/Heading/Heading.md
  src/core/Heading/Heading.test.tsx
  src/core/Heading/Heading.tsx
  src/core/Heading/__snapshots__/Heading.test.tsx.snap
  src/reset/HtmlH/HtmlH.tsx
  yarn.lock
Labels: DX, dependencies
