Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2019-04, with the labels that each got.

#50 Feature/gh pages integration
  .circleci/config.yml
  package.json
  yarn.lock
Labels: enhancement

#52 Bugfix/fix styleguide build
  .circleci/config.yml
  src/index.tsx
Labels: bug

#56 Fix user-selectable value to be user-select
  src/core/Button/Button.baseStyles.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
Labels: bug

#58 Feature/panel expansion group
  src/components/Panel/PanelExpansion.tsx
  src/components/Panel/PanelExpansionGroup.tsx
  src/components/utils/pseudo.ts
  src/core/Panel/Panel.md
  src/core/Panel/Panel.tsx
  src/core/Panel/PanelExpansion.baseStyles.tsx
  src/core/Panel/PanelExpansionGroup.baseStyles.tsx
  src/core/Panel/PanelExpansionGroup.tsx
  src/core/Panel/__snapshots__/PanelExpansion.test.tsx.snap
  src/core/theme/colors.ts
  src/core/theme/index.ts
  src/core/theme/transitions.ts
Labels: enhancement

#61 Bugfix/panel expansion group styles
  src/components/Panel/PanelExpansion.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/Panel/Panel.md
  src/core/Panel/Panel.tsx
  src/core/Panel/PanelExpansion.baseStyles.tsx
  src/core/Panel/PanelExpansionGroup.tsx
  src/core/Panel/__snapshots__/PanelExpansion.test.tsx.snap
  src/core/theme/colors.ts
  src/core/theme/utils/defaultTheme.ts
  src/core/theme/utils/outline.ts
  src/core/theme/zindexes.ts
Labels: bug

#62 Refactor remove not needed state toggleAll
  src/components/Panel/PanelExpansionGroup.tsx
Labels: DX

#63 Feature/breadcrumb
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Form/Toggle.tsx
  src/components/Link/Link.tsx
  src/components/Panel/PanelExpansion.tsx
  src/components/index.ts
  src/core/Breadcrumb/Breadcrumb.baseStyles.ts
  src/core/Breadcrumb/Breadcrumb.md
  src/core/Breadcrumb/Breadcrumb.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/Link/Link.baseStyles.ts
  src/core/Link/Link.tsx
  src/core/Panel/PanelExpansion.baseStyles.tsx
  src/core/Panel/PanelExpansion.tsx
  src/core/Panel/PanelExpansionGroup.tsx
  src/core/Panel/__snapshots__/PanelExpansion.test.tsx.snap
  src/core/theme/reset/index.ts
  src/core/theme/typography.ts
  src/core/theme/utils/defaultTheme.ts
  src/index.tsx
  src/reset/HtmlA/HtmlA.tsx
  src/reset/HtmlLi/HtmlLi.tsx
  src/reset/HtmlNav/HtmlNav.tsx
  src/reset/HtmlOl/HtmlOl.tsx
  src/reset/index.ts
  src/reset/utils/index.ts
  src/utils/css/pseudo.ts
Labels: enhancement

#65 Bugfix/panel expansion group margins
  src/core/Panel/PanelExpansion.baseStyles.tsx
  src/core/Panel/PanelExpansionGroup.baseStyles.tsx
  src/core/Panel/__snapshots__/PanelExpansion.test.tsx.snap
Labels: bug, enhancement

#68 Add background color for Menu.language
  src/core/Menu/Menu.baseStyles.tsx
Labels: bug
