Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2019-12, with the labels that each got.

#267 [BreakingChange] Remove support for custom SVG with Icon
  src/components/Icon/Icon.tsx
  src/components/Svg/Svg.test.tsx
  src/components/Svg/Svg.tsx
  src/components/Svg/__snapshots__/Svg.test.tsx.snap
  src/components/Svg/test.svg
  src/components/index.ts
  src/core/Button/Button.tsx
  src/core/Icon/Icon.baseStyles.tsx
  src/core/Icon/Icon.md
  src/core/Icon/Icon.test.tsx
  src/core/Icon/Icon.tsx
Labels: WIP, enhancement

#269 [BreakingChange] Export only suomifi-design-system tokens
  .styleguidist/spacing.md
  .styleguidist/typography.md
  DEVELOPMENT.md
  package.json
  src/core/Breadcrumb/Breadcrumb.baseStyles.ts
  src/core/Breadcrumb/BreadcrumbLink.tsx
  src/core/Button/Button.tsx
  src/core/Colors/Colors.baseStyles.tsx
  src/core/Colors/Colors.tsx
  src/core/Icon/Icon.tsx
  src/core/Panel/PanelExpansion.tsx
  src/core/Text/Text.baseStyles.ts
  src/core/theme/colors.ts
  src/core/theme/index.ts
  src/core/theme/reset/index.ts
  src/core/theme/spacing.ts
  src/core/theme/tokens.test.tsx
  src/core/theme/typography.ts
  src/core/theme/utils/colors.ts
  src/core/theme/utils/index.ts
  src/core/theme/utils/outline.ts
  src/core/theme/utils/spacing.ts
  src/core/theme/utils/typography/fontsize.ts
  src/core/theme/utils/typography/index.ts
  src/core/theme/utils/typography/typographyutil.ts
  src/index.tsx
  yarn.lock
Labels: enhancement

#271 Release 0.4.0
  package.json
Labels: release

#272 Release 0.4.1
  package.json
  src/core/Icon/Icon.md
  yarn.lock
Labels: release
