Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2020-08, with the labels that each got.

#379 [Fix] Checkbox's hintText style for font
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Labels: bug

#375 [Feature] name and value props for Checkbox
  src/components/Form/Checkbox.tsx
  src/core/Form/Checkbox/Checkbox.test.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Labels: bug, enhancement

#378 [Feature] TextInput improvements
  src/components/Form/TextInput.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: enhancement

#376 [Feature] Textarea component
  .styleguidist/styleguidist.sections.js
  src/components/Form/Textarea.tsx
  src/components/index.ts
  src/core/Form/Textarea/Textarea.baseStyles.tsx
  src/core/Form/Textarea/Textarea.md
  src/core/Form/Textarea/Textarea.test.tsx
  src/core/Form/Textarea/Textarea.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/index.tsx
  src/reset/HtmlTextarea/HtmlTextarea.tsx
  src/reset/index.ts
Labels: enhancement

#381 [Update] Update webpack and styleguidist to latest stable releases
  package.json
  yarn.lock
Labels: dependencies

#377 [Feature] Radiobutton
  .gitignore
  .styleguidist/styleguidist.sections.js
  src/components/Form/RadioButton.tsx
  src/components/Form/RadioButtonDivider.tsx
  src/components/Form/RadioButtonGroup.tsx
  src/components/index.ts
  src/core/Form/Form.tsx
  src/core/Form/RadioButton/RadioButton.baseStyles.tsx
  src/core/Form/RadioButton/RadioButton.md
  src/core/Form/RadioButton/RadioButton.test.tsx
  src/core/Form/RadioButton/RadioButton.tsx
  src/core/Form/RadioButton/RadioButtonDivider.baseStyles.tsx
  src/core/Form/RadioButton/RadioButtonDivider.tsx
  src/core/Form/RadioButton/RadioButtonGroup.baseStyles.tsx
  src/core/Form/RadioButton/RadioButtonGroup.md
  src/core/Form/RadioButton/RadioButtonGroup.test.tsx
  src/core/Form/RadioButton/RadioButtonGroup.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/index.tsx
Labels: enhancement

#382 [BugFix] Upgrade suomifi-icons to latest 1.0.1.
  yarn.lock
Labels: dependencies

#383 [BugFix] discard passProps tokens for unStyled Button
  src/core/Button/UnstyledButton.tsx
  src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
Labels: bug

#384 [Release] 1.1.0
  package.json
Labels: release

#385 Update master to latest 1.1.0
  .gitignore
  .styleguidist/styleguidist.sections.js
  package.json
  src/components/Form/Checkbox.tsx
  src/components/Form/RadioButton.tsx
  src/components/Form/RadioButtonDivider.tsx
  src/components/Form/RadioButtonGroup.tsx
  src/components/Form/TextInput.tsx
  src/components/Form/Textarea.tsx
  src/components/index.ts
  src/core/Button/UnstyledButton.tsx
  src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/Checkbox.test.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/Form.tsx
  src/core/Form/RadioButton/RadioButton.baseStyles.tsx
  src/core/Form/RadioButton/RadioButton.md
  src/core/Form/RadioButton/RadioButton.test.tsx
  src/core/Form/RadioButton/RadioButton.tsx
  src/core/Form/RadioButton/RadioButtonDivider.baseStyles.tsx
  src/core/Form/RadioButton/RadioButtonDivider.tsx
  src/core/Form/RadioButton/RadioButtonGroup.baseStyles.tsx
  src/core/Form/RadioButton/RadioButtonGroup.md
  src/core/Form/RadioButton/RadioButtonGroup.test.tsx
  src/core/Form/RadioButton/RadioButtonGroup.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/Textarea.baseStyles.tsx
  src/core/Form/Textarea/Textarea.md
  src/core/Form/Textarea/Textarea.test.tsx
  src/core/Form/Textarea/Textarea.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/index.tsx
  src/reset/HtmlTextarea/HtmlTextarea.tsx
  src/reset/index.ts
  yarn.lock
Labels: enhancement

#386 [Feature] Add name prop to form component APIs
  src/components/Form/TextInput.tsx
  src/components/Form/Textarea.tsx
  src/components/Form/Toggle.tsx
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/Textarea/Textarea.test.tsx
  src/core/Form/Toggle/Toggle.test.tsx
Labels: enhancement

#387 [Feature] Add logger warning to checkbox when name or value props have an empty value
  src/components/Form/Checkbox.tsx
Labels: enhancement
