Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2020-02, with the labels that each got.

#280 [Feature] Changed to use tsdx, tslint changed to eslint and others
  .circleci/config.yml
  .eslintrc
  .styleguidist/webpack.config.js
  README.md
  jest.setup.js
  package.json
  src/components/Block/Block.tsx
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/LanguageMenu/LanguageMenu.tsx
  src/components/Panel/PanelExpansion.tsx
  src/core/Block/Block.test.tsx
  src/core/Breadcrumb/Breadcrumb.test.tsx
  src/core/Breadcrumb/Breadcrumb.tsx
  src/core/Breadcrumb/BreadcrumbLink.tsx
  src/core/Button/Button.test.tsx
  src/core/Colors/Colors.test.tsx
  src/core/Form/SearchInput/SearchInput.test.tsx
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/Toggle/Toggle.test.tsx
  src/core/Heading/Heading.test.tsx
  src/core/Icon/Icon.test.tsx
  src/core/Icon/Icon.tsx
  src/core/Icon/__snapshots__/Icon.test.tsx.snap
  src/core/Link/Link.test.tsx
  src/core/Link/Link.tsx
  src/core/Link/LinkExternal.test.tsx
  src/core/Panel/Panel.tsx
  src/core/Panel/PanelExpansion.test.tsx
  src/core/Panel/PanelExpansion.tsx
  src/core/Paragraph/Paragraph.test.tsx
  src/core/Text/Text.test.tsx
  src/core/Text/__snapshots__/Text.test.tsx.snap
  src/core/theme/colors.ts
  src/core/theme/icons.ts
  src/core/theme/index.ts
  src/core/theme/spacing.ts
  src/core/theme/tokens.test.tsx
  src/core/theme/utils/defaults.ts
  src/utils/css/utils.ts
  styleguide.config.js
  tsconfig.es2015.json
  tsconfig.esm.json
  tsconfig.json
  tsdx.config.js
  tslint.json
  yarn.lock
Labels: DX, enhancement

#279 [Bugfix] Make toggle input match icon size
  src/core/Form/Toggle/Toggle.baseStyles.tsx
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
Labels: bug

#281 Release 0.5.0
  package.json
Labels: release

#282 Feature/isolate css processing
  README.md
  globalCss.js
  package.json
  src/components/Dropdown/Dropdown.tsx
  src/components/LanguageMenu/LanguageMenu.tsx
  src/core/theme/fontFaces.css
  src/index.tsx
  tsdx.config.js
  yarn.lock
Labels: bug, enhancement

#283 Release 0.6.0
  package.json
Labels: release

#284 [Bugfix]Toggle focus
  src/components/Form/ToggleInput.tsx
  src/core/Form/Toggle/Toggle.baseStyles.tsx
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
Labels: bug

#285 [Bugfix] Fix breadcrumb alignment
  src/core/Breadcrumb/Breadcrumb.baseStyles.ts
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
Labels: bug

#286 Feature/update reach
  .styleguidist/styleguidist.require.js
  package.json
  src/components/Component-component/Component-component.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/LanguageMenu/LanguageMenu.tsx
  src/components/index.ts
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/Dropdown.tsx
  src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
  src/core/LanguageMenu/LanguageMenu.tsx
  types/index.d.ts
  yarn.lock
Labels: bug, dependencies

#287 [Feature] Update to use suomifi-icons version 0.0.14
  package.json
  yarn.lock
Labels: Important, dependencies

#288 Release 0.6.1
  package.json
Labels: release
