Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2020-09, with the labels that each got.

#388 [Feature] Aria-invalid attributes
  src/components/Form/Checkbox.tsx
  src/components/Form/TextInput.tsx
  src/components/Form/Textarea.tsx
  src/core/Form/Checkbox/Checkbox.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/Textarea.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
Labels: Accessibility, bug, enhancement

#389 [BugFix] Upgrade vulnerable dependencies
  package.json
  yarn.lock
Labels: dependencies, security

#390 [Feature] Chip component
  .styleguidist/styleguidist.sections.js
  src/core/Chip/Chip.baseStyles.tsx
  src/core/Chip/Chip.md
  src/core/Chip/Chip.test.tsx
  src/core/Chip/Chip.tsx
  src/core/Chip/__snapshots__/Chip.test.tsx.snap
  src/index.tsx
Labels: enhancement

#392 [Feature] Popover component
  .eslintrc
  package.json
  src/core/Popover/Popover.tsx
  yarn.lock
Labels: enhancement

#394 [Feature] Text input icon support
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: enhancement
