Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2020-05, with the labels that each got.

#321 Replace UNSAFE_componentWillReceiveProps with getDerivedStateFromProps
  src/components/Form/Toggle.tsx
  src/components/Form/ToggleButton.tsx
  src/components/Form/ToggleInput.tsx
  src/core/Form/Toggle/Toggle.md
  src/core/Form/Toggle/Toggle.test.tsx
  src/core/Form/Toggle/Toggle.tsx
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
Labels: enhancement

#315 [Feature] Add checkbox component
  .styleguidist/styleguidist.sections.js
  src/components/Form/Checkbox.tsx
  src/components/index.ts
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/Checkbox.md
  src/core/Form/Checkbox/Checkbox.test.tsx
  src/core/Form/Checkbox/Checkbox.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/Form.tsx
  src/index.tsx
Labels: enhancement

#324 [Fix] Focus style align with style guide
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/__snapshots__/Link.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/core/theme/colors.ts
  src/core/theme/radius.ts
  src/core/theme/utils/focus.ts
  src/core/theme/utils/outline.ts
Labels: enhancement

#325 [Feature] Add non-pseudo focus style
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/__snapshots__/Link.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/core/theme/colors.ts
  src/core/theme/utils/focus.ts
  src/core/theme/utils/outline.ts
Labels: enhancement

#326 [Release] 0.14.0
  package.json
Labels: release

#328 [Feature] Align button styles with style guide
  src/core/Button/Button.baseStyles.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/core/theme/colors.ts
  src/core/theme/reset/index.ts
Labels: enhancement

#331 [Feature] Align dropdown styles with style guide
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/theme/colors.ts
  src/core/theme/reset/index.ts
Labels: enhancement

#332 [Bugfix] Align textinput and searchinput styles with design
  src/components/Form/TextInput.tsx
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: bug

#333 [Feature] Add new instructions to Readme and FAQ
  FAQ.md
  README.md
Labels: enhancement

#335 [Feature] Update textinput styles to include inner shadow
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/theme/colors.ts
Labels: enhancement

#334 [Fix]README update
  README.md
Labels: enhancement

#336 [Feature] Align toggle styles with style guide
  package.json
  src/core/Form/Toggle/Toggle.baseStyles.tsx
  src/core/Form/Toggle/Toggle.md
  src/core/Form/Toggle/Toggle.tsx
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  yarn.lock
Labels: enhancement

#337 [Release] 0.15.0
  package.json
Labels: release

#339 [Feature] Improve pull request template.
  .github/pull_request_template.md
Labels: enhancement

#340 [Fix] Update reach dependencies
  package.json
  yarn.lock
Labels: bug, dependencies

#341 [Release] 0.15.1
  package.json
Labels: release
