Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2020-12, with the labels that each got.

#413 [Feature] Textarea adjustments
  src/components/Form/Textarea.tsx
  src/components/index.ts
  src/components/utils/aria.ts
  src/core/Form/Textarea/Textarea.baseStyles.tsx
  src/core/Form/Textarea/Textarea.md
  src/core/Form/Textarea/Textarea.test.tsx
  src/core/Form/Textarea/Textarea.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/core/Icon/Icon.tsx
  src/core/StaticIcon/StaticIcon.tsx
  src/core/theme/colors.ts
  src/utils/aria.test.ts
  src/utils/aria.ts
Labels: DX, bug, enhancement

#417 [Feature] Debounce component
  src/core/Form/SearchInput/SearchInput.md
  src/core/Form/SearchInput/SearchInput.test.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/TextInput/TextInput.tsx
  src/core/utils/Debounce/Debounce.test.tsx
  src/core/utils/Debounce/Debounce.tsx
Labels: enhancement

#418 [Release] 3.0.0-beta.0.
  package.json
Labels: release

#421 [Feature] Upgrade dependencies
  README.md
  package.json
  src/components/Dropdown/Dropdown.tsx
  src/components/LanguageMenu/LanguageMenu.tsx
  src/core/Breadcrumb/Breadcrumb.tsx
  src/core/Button/Button.baseStyles.tsx
  src/core/Button/Button.tsx
  src/core/Expander/Expander/Expander.baseStyles.tsx
  src/core/Expander/Expander/Expander.test.tsx
  src/core/Expander/ExpanderContent/ExpanderContent.baseStyles.tsx
  src/core/Expander/ExpanderTitle/ExpanderTitle.baseStyles.tsx
  src/core/Expander/ExpanderTitle/ExpanderTitle.tsx
  src/core/Expander/ExpanderTitleButton/ExpanderTitleButton.baseStyles.tsx
  src/core/Expander/ExpanderTitleButton/ExpanderTitleButton.tsx
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/Checkbox.tsx
  src/core/Form/RadioButton/RadioButton.baseStyles.tsx
  src/core/Form/RadioButton/RadioButton.tsx
  src/core/Form/RadioButton/RadioButtonDivider.baseStyles.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/Toggle/Toggle.tsx
  src/core/Heading/Heading.baseStyles.ts
  src/core/Icon/Icon.tsx
  src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
  src/core/LanguageMenu/LanguageMenu.tsx
  src/core/Link/Link.baseStyles.ts
  src/core/StaticIcon/StaticIcon.tsx
  src/core/theme/index.ts
  src/core/theme/reset/index.ts
  src/utils/aria.ts
  tsdx.config.js
  yarn.lock
Labels: dependencies, security

#420 [Feature] Button soft disabled
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/index.ts
  src/core/Button/Button.baseStyles.tsx
  src/core/Button/Button.md
  src/core/Button/Button.test.tsx
  src/core/Button/Button.tsx
  src/core/Button/UnstyledButton.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/index.tsx
Labels: Accessibility, DX, enhancement
