Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2020-04, with the labels that each got.

#308 [Feature] Tsdx css configuration
  .styleguidist/webpack.config.js
  globalCss.js
  jest.config.js
  jest.styleMock.js
  package.json
  src/core/theme/fontFaces.css
  src/core/theme/index.ts
  src/index.tsx
  src/styles.scss
  tsdx.config.js
  yarn.lock
Labels: enhancement

#309 [Feature] Update all dependencies to latest
  .eslintrc
  .styleguidist/styleguideTsconfig.json
  .styleguidist/webpack.config.js
  package.json
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Expander/Expander.tsx
  src/components/Expander/ExpanderGroup.tsx
  src/components/Form/ToggleButton.tsx
  src/components/Form/ToggleInput.tsx
  src/components/LanguageMenu/LanguageMenu.tsx
  src/core/Block/Block.tsx
  src/core/Block/__snapshots__/Block.test.tsx.snap
  src/core/Breadcrumb/Breadcrumb.tsx
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Button/Button.tsx
  src/core/Button/UnstyledButton.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Dropdown/Dropdown.tsx
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Expander/Expander.tsx
  src/core/Expander/ExpanderGroup.tsx
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Form/SearchInput/SearchInput.md
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Toggle/Toggle.tsx
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/Heading/Heading.tsx
  src/core/Heading/__snapshots__/Heading.test.tsx.snap
  src/core/Icon/Icon.baseStyles.tsx
  src/core/Icon/Icon.md
  src/core/Icon/Icon.tsx
  src/core/Icon/__snapshots__/Icon.test.tsx.snap
  src/core/LanguageMenu/LanguageMenu.tsx
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/Link.tsx
  src/core/Link/LinkExternal.tsx
  src/core/Link/__snapshots__/Link.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/Paragraph/Paragraph.tsx
  src/core/Paragraph/__snapshots__/Paragraph.test.tsx.snap
  src/core/StaticIcon/StaticIcon.md
  src/core/StaticIcon/StaticIcon.tsx
  src/core/StaticIcon/__snapshots__/StaticIcon.test.tsx.snap
  src/core/Text/Text.tsx
  src/core/Text/__snapshots__/Text.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/reset/utils/index.ts
  src/utils/css/pseudo.ts
  src/utils/css/utils.ts
  src/utils/test/axe.ts
  src/utils/uuid.ts
  tsconfig.json
  yarn.lock
Labels: dependencies

#317 [Release] 0.12.0
  package.json
Labels: release

#318 [BugFix] skipLibCheck related type issues
  .styleguidist/webpack.config.js
  README.md
  package.json
  tsconfig.json
  types/index.d.ts
  yarn.lock
Labels: bug, dependencies

#320 [Release] 0.13.0
  package.json
Labels: release

#305 [Feature] Skip variant added for Link
  .styleguidist/styleguidist.sections.js
  src/components/Link/LinkSkip.tsx
  src/core/Link/Link.baseStyles.ts
  src/core/Link/Link.md
  src/core/Link/Link.tsx
  src/core/Link/LinkSkip.md
  src/core/Link/LinkSkip.tsx
  src/index.tsx
Labels: enhancement
