Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2020-03, with the labels that each got.

#289 [Bugfix] Button's Assertive component
  src/components/Button/Button.tsx
Labels: bug, enhancement

#290 Icons split to Icon, StaticIcon and ComponentIcon
  .styleguidist/styleguidist.sections.js
  package.json
  src/core/Button/Button.tsx
  src/core/Form/Toggle/Toggle.tsx
  src/core/Icon/Icon.baseStyles.tsx
  src/core/Icon/Icon.md
  src/core/Icon/Icon.tsx
  src/core/StaticIcon/StaticIcon.md
  src/core/StaticIcon/StaticIcon.test.tsx
  src/core/StaticIcon/StaticIcon.tsx
  src/core/StaticIcon/__snapshots__/StaticIcon.test.tsx.snap
  src/index.tsx
  yarn.lock
Labels: bug, dependencies, enhancement

#293 0.7.0
  package.json
Labels: release

#294 [Breakinghange] Update library to use design tokens version 0.7.1
  .styleguidist/spacing.md
  package.json
  src/core/Button/Button.baseStyles.tsx
  src/core/Colors/__snapshots__/Colors.test.tsx.snap
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Expander/Expander.baseStyles.tsx
  src/core/Form/Toggle/Toggle.baseStyles.tsx
  src/core/Icon/Icon.tsx
  src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
  src/core/Link/Link.baseStyles.ts
  src/core/theme/colors.ts
  yarn.lock
Labels: dependencies

#296 Release 0.8.0
  package.json
Labels: release

#297 [Bugfix] Allow the input-field to take all width it can on the TextInput
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: bug

#298 [Feature] Language menu improvements
  src/components/LanguageMenu/LanguageMenu.tsx
  src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
  src/core/LanguageMenu/LanguageMenu.tsx
Labels: enhancement

#295 [Feature] TextInput state text & colors
  src/components/Form/TextInput.tsx
  src/core/Form/SearchInput/SearchInput.test.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: enhancement

#299 Release 0.9.0
  package.json
Labels: release

#300 [BugFix] Language menu positioning
  package.json
  src/components/Dropdown/Dropdown.tsx
  src/components/LanguageMenu/LanguageMenu.tsx
  src/components/index.ts
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/Dropdown.test.tsx
  src/core/Dropdown/Dropdown.tsx
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
  src/core/LanguageMenu/LanguageMenu.md
  src/core/LanguageMenu/LanguageMenu.test.tsx
  src/core/LanguageMenu/LanguageMenu.tsx
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/utils/test/axe.ts
  types/index.d.ts
  yarn.lock
Labels: Accessibility, bug, dependencies

#301 0.10.0
  package.json
Labels: release

#303 [Feature] Update documentation
  .styleguidist/components.md
  .styleguidist/introduction.md
  README.md
Labels: enhancement

#302 [BreakingChange] Update to 5px based spacing and inset spacing.
  .styleguidist/spacing.md
  package.json
  src/core/Block/Block.md
  src/core/Block/Block.test.tsx
  src/core/Block/Block.tsx
  src/core/Block/__snapshots__/Block.test.tsx.snap
  src/core/Button/Button.baseStyles.tsx
  src/core/Colors/Colors.baseStyles.tsx
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Expander/Expander.baseStyles.tsx
  src/core/Expander/ExpanderGroup.baseStyles.tsx
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/Toggle/Toggle.baseStyles.tsx
  src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
  src/core/Link/Link.baseStyles.ts
  src/core/Paragraph/Paragraph.tsx
  src/core/Text/Text.md
  src/core/Text/Text.test.tsx
  src/core/Text/__snapshots__/Text.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/core/theme/reset/index.ts
  src/core/theme/spacing.ts
  src/core/theme/utils/spacing.ts
  yarn.lock
Labels: enhancement

#304 [Release] 0.11.0
  package.json
Labels: release

#306 [Fix] Link's styleguidist page
  src/core/Link/Link.tsx
  src/index.tsx
Labels: bug

#307 [Feature] Added note to run 'yarn' after pulling changes from the repo
  DEVELOPMENT.md
Labels: DX
