Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2020-10, with the labels that each got.

#393 [Feature] Text Input and Search Input style improvements
  src/components/Form/TextInput.tsx
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: enhancement

#395 [Bugfix] Disabled chip color and cursor
  src/core/Chip/Chip.baseStyles.tsx
  src/core/Chip/__snapshots__/Chip.test.tsx.snap
Labels: bug

#396 [Bugfix] Disabled text input icon color
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: bug

#397 [Feature] Update readme to cover alternative css imports
  README.md
Labels: enhancement

#398 [Feature] Text input optionalText prop
  src/components/Form/TextInput.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: enhancement

#399 [Feature] Create separate styling for selected items in dropdown
  src/components/Dropdown/Dropdown.tsx
  src/core/Dropdown/Dropdown.baseStyles.tsx
Labels: enhancement

#401 [Feature] Dropdown disabled state
  src/components/Dropdown/Dropdown.tsx
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/Dropdown.md
  src/core/Dropdown/Dropdown.test.tsx
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Labels: enhancement

#403 [Feature] Export VisuallyHidden from the library
  .styleguidist/styleguidist.sections.js
  src/core/VisuallyHidden/VisuallyHidden.md
  src/core/VisuallyHidden/VisuallyHidden.tsx
  src/index.tsx
Labels: enhancement

#400 [Feature] Search input clear and submit
  src/components/Form/SearchInput.tsx
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Chip/__snapshots__/Chip.test.tsx.snap
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/LabelText/LabelText.baseStyles.tsx
  src/core/Form/LabelText/LabelText.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/SearchInput.md
  src/core/Form/SearchInput/SearchInput.test.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/StatusText/StatusText.baseStyles.tsx
  src/core/Form/StatusText/StatusText.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/__snapshots__/Link.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/core/theme/utils/outline.ts
  src/reset/HtmlInput/HtmlInput.tsx
  src/reset/index.ts
Labels: Accessibility, enhancement

#404 [Bugfix] Move Chip example inline styling to wrapping element
  src/core/Chip/Chip.md
Labels: bug

#405 [Feature] Fix and rewrite focus styling
  src/components/Form/Textarea.tsx
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Button/Button.baseStyles.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Chip/Chip.baseStyles.tsx
  src/core/Chip/__snapshots__/Chip.test.tsx.snap
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Expander/Expander.baseStyles.tsx
  src/core/Expander/ExpanderGroup.baseStyles.tsx
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/RadioButton/RadioButton.baseStyles.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/Textarea.baseStyles.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/core/Form/Toggle/Toggle.baseStyles.tsx
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/Link.baseStyles.ts
  src/core/Link/__snapshots__/Link.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/core/theme/reset/index.ts
  src/core/theme/utils/focus.ts
  src/core/theme/utils/index.ts
Labels: bug

#406 Release 2.0.0
  package.json
Labels: release
