Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2020-11, with the labels that each got.

#409 [Feature] Upgrade dependencies to latest
  .eslintrc
  .styleguidist/styleguidist.sections.js
  README.md
  jest.config.js
  package.json
  src/components/Expander/Expander.tsx
  src/core/Block/Block.baseStyles.ts
  src/core/Breadcrumb/Breadcrumb.baseStyles.ts
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Button/Button.baseStyles.tsx
  src/core/Expander/Expander.baseStyles.tsx
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/RadioButton/RadioButton.baseStyles.tsx
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/Toggle/Toggle.baseStyles.tsx
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/Heading/Heading.baseStyles.ts
  src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
  src/core/Link/Link.baseStyles.ts
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/Paragraph/Paragraph.baseStyles.ts
  src/core/Text/Text.baseStyles.ts
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/core/theme/utils/outline.ts
  styleguide.config.js
  yarn.lock
Labels: dependencies, enhancement

#408 [Fix] LanguageMenu text wrapping
  src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
  src/core/LanguageMenu/LanguageMenu.tsx
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
Labels: bug

#410 [Feature] Update suomifi-icons and suomifi-design-tokens dependencies
  package.json
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Chip/__snapshots__/Chip.test.tsx.snap
  src/core/Colors/__snapshots__/Colors.test.tsx.snap
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/RadioButton/RadioButton.baseStyles.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/Textarea.baseStyles.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/__snapshots__/Link.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  yarn.lock
Labels: enhancement

#411 [Feature] TextInput improvements
  src/components/Form/TextInput.tsx
  src/components/index.ts
  src/core/Form/HintText/HintText.baseStyles.tsx
  src/core/Form/HintText/HintText.test.tsx
  src/core/Form/HintText/HintText.tsx
  src/core/Form/LabelText/LabelText.baseStyles.tsx
  src/core/Form/LabelText/LabelText.test.tsx
  src/core/Form/LabelText/LabelText.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/StatusText/StatusText.test.tsx
  src/core/Form/StatusText/StatusText.tsx
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/types.ts
Labels: DX, enhancement

#412 [Feature] Checkbox adjustments
  LICENSE
  src/components/Form/Checkbox.tsx
  src/components/index.ts
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/Checkbox.md
  src/core/Form/Checkbox/Checkbox.test.tsx
  src/core/Form/Checkbox/Checkbox.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Popover/Popover.tsx
  src/utils/AutoId.tsx
  src/utils/common.ts
Labels: DX, enhancement
