Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2020-07, with the labels that each got.

#368 Release 1.0.0
  package.json
Labels: release

#369 Release 1.0.0
  .styleguidist/styleguidist.require.js
  jest.config.js
  package.json
  src/components/Dropdown/Dropdown.tsx
  src/components/Form/SearchInput.tsx
  src/components/Form/TextInput.tsx
  src/core/Breadcrumb/BreadcrumbLink.tsx
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Button/Button.baseStyles.tsx
  src/core/Button/Button.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/Dropdown.md
  src/core/Dropdown/Dropdown.test.tsx
  src/core/Dropdown/Dropdown.tsx
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/Checkbox.test.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/SearchInput.md
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Toggle/Toggle.baseStyles.tsx
  src/core/Form/Toggle/Toggle.md
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/Icon/Icon.md
  src/core/Icon/Icon.tsx
  src/core/Icon/__snapshots__/Icon.test.tsx.snap
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/Text/Text.md
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/core/theme/colors.ts
  src/styles.scss
  types/index.d.ts
  yarn.lock
Labels: release

#371 [Fix] Disable generated button with disabled-attribute
  src/components/Button/Button.tsx
  src/core/Button/Button.test.tsx
Labels: bug

#372 [Release] 1.0.1
  package.json
Labels: release

#373 Update master to latest 1.0.1
  package.json
  src/components/Button/Button.tsx
  src/core/Button/Button.test.tsx
Labels: enhancement
