Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2020-06, with the labels that each got.

#344 Remove mouse-events from focus pseudo element
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/__snapshots__/Link.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/core/theme/utils/outline.ts
Labels: bug

#345 0.15.2
  package.json
Labels: release

#330 [Fix] Expander's defaultOpen, open and onClick properties not working when inside ExpanderGroup
  src/components/Expander/Expander.tsx
  src/components/Expander/ExpanderGroup.tsx
  src/core/Expander/Expander.md
  src/core/Expander/Expander.test.tsx
  src/core/Expander/Expander.tsx
  src/core/Expander/ExpanderGroup.test.tsx
  src/core/Expander/ExpanderGroup.tsx
  src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap
Labels: bug

#338 [Fix] Grouped expanders corners rounded and separator between
  src/components/Expander/Expander.tsx
  src/core/Expander/ExpanderGroup.baseStyles.tsx
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
Labels: bug

#346 [Bugfix] Fix incorrect internal state handling in checkbox
  src/components/Form/Checkbox.tsx
Labels: bug

#342 [Feature] Adjust link focus styles
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Link/Link.baseStyles.ts
  src/core/Link/__snapshots__/Link.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
Labels: enhancement

#348 [Fix] Remove mentions of bare accessible components as it is not possible
  .styleguidist/modules.md
  .styleguidist/primitive.md
  src/components/README.md
Labels: bug

#347 [Bugfix] Set checkbox and toggle input variant to use event data for state change
  src/components/Form/Checkbox.tsx
  src/components/Form/ToggleInput.tsx
Labels: Accessibility, bug

#351 [Feature] Align languagemenu styles with design
  src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
  src/core/LanguageMenu/LanguageMenu.md
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
Labels: enhancement

#352 [Fix] CheckBox hintText to use different color token
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Labels: bug

#353 [Release] 0.16.0
  package.json
Labels: release

#354 [Bugfix] Replace wrong token in languagemenu styles
  src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
Labels: bug

#355 [Release] 0.16.1
  package.json
Labels: release

#357 [Fix] Button style fixes
  src/core/Button/Button.baseStyles.tsx
  src/core/Button/Button.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/theme/colors.ts
Labels: bug

#358 [Feature] Add visual placeholder for TextInput
  src/components/Form/SearchInput.tsx
  src/components/Form/TextInput.tsx
  src/core/Form/SearchInput/SearchInput.md
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: enhancement

#359 [Fix] Icons to use currentColor
  src/core/Breadcrumb/BreadcrumbLink.tsx
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Icon/Icon.md
  src/core/Icon/Icon.tsx
  src/core/Icon/__snapshots__/Icon.test.tsx.snap
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
Labels: DX, enhancement

#361 [Bugfix] Checkbox statustext margins
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/Checkbox.test.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Labels: bug

#360 [Feature] Dropdown label and placeholder
  src/components/Dropdown/Dropdown.tsx
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/Dropdown.md
  src/core/Dropdown/Dropdown.test.tsx
  src/core/Dropdown/Dropdown.tsx
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  types/index.d.ts
Labels: Accessibility, bug, enhancement

#362 [Bugfix] Toggle focus styles not applied to first instance
  src/core/Form/Toggle/Toggle.baseStyles.tsx
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
Labels: bug

#364 [Feature] Locking Reach UI versions with resolutions
  package.json
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  yarn.lock
Labels: enhancement

#363 [Feature] Dropdown value property
  .styleguidist/styleguidist.require.js
  jest.config.js
  package.json
  src/components/Dropdown/Dropdown.tsx
  src/core/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/Dropdown.md
  src/core/Dropdown/Dropdown.test.tsx
  src/core/Dropdown/Dropdown.tsx
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/styles.scss
  yarn.lock
Labels: enhancement

#365 [Feature] Update suomifi-icons and design-tokens
  package.json
  yarn.lock
Labels: dependencies, enhancement

#366 [Release] 0.17.0
  package.json
Labels: release

#367 [Fix] Changes to examples
  src/core/Dropdown/Dropdown.md
  src/core/Form/Toggle/Toggle.md
  src/core/Text/Text.md
Labels: bug
