Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2021-04, with the labels that each got.

#452 [Fix] ExpanderGroup performance improvements
  src/core/Expander/Expander/Expander.tsx
  src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/ExpanderGroup/ExpanderGroup.tsx
  src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Expander/ExpanderTitle/ExpanderTitle.baseStyles.tsx
  src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap
  src/core/Expander/ExpanderTitleButton/ExpanderTitleButton.baseStyles.tsx
  src/core/Expander/ExpanderTitleButton/__snapshots__/ExpanderTitleButton.test.tsx.snap
Labels: DX, bug, enhancement

#456 [Fix] Text component color prop
  src/core/Form/Toggle/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap
  src/core/Form/Toggle/ToggleInput/__snapshots__/ToggleInput.test.tsx.snap
  src/core/Text/Text.baseStyles.ts
  src/core/Text/Text.tsx
Labels: bug

#455 [Feature] Update documentation
  CONTRIBUTING.md
  DEVELOPMENT.md
  FAQ.md
  README.md
Labels: enhancement

#457 Fix/modal mobile focus lock
  src/core/Modal/Modal/Modal.baseStyles.tsx
  src/core/Modal/Modal/Modal.test.tsx
  src/core/Modal/Modal/Modal.tsx
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
  src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
Labels: Accessibility, bug

#459 Fix/expander styles and aria support
  src/core/Expander/Expander/Expander.md
  src/core/Expander/Expander/Expander.test.tsx
  src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/ExpanderContent/ExpanderContent.baseStyles.tsx
  src/core/Expander/ExpanderContent/__snapshots__/ExpanderContent.test.tsx.snap
  src/core/Expander/ExpanderGroup/ExpanderGroup.test.tsx
  src/core/Expander/ExpanderGroup/ExpanderGroup.tsx
  src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Expander/ExpanderTitle/ExpanderTitle.test.tsx
  src/core/Expander/ExpanderTitle/ExpanderTitle.tsx
  src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap
  src/core/Expander/ExpanderTitleButton/ExpanderTitleButton.test.tsx
  src/core/Expander/ExpanderTitleButton/ExpanderTitleButton.tsx
Labels: Accessibility, bug

#460 Fix/modal initial focus and width
  src/core/Modal/Modal/Modal.baseStyles.tsx
  src/core/Modal/Modal/Modal.md
  src/core/Modal/Modal/Modal.test.tsx
  src/core/Modal/Modal/Modal.tsx
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
  src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
  src/core/Modal/ModalTitle/ModalTitle.baseStyles.tsx
  src/core/Modal/ModalTitle/ModalTitle.tsx
Labels: Accessibility, enhancement

#463 Feature/update deps
  .husky/.gitignore
  .husky/common.sh
  .husky/pre-commit
  .husky/pre-push
  package.json
  src/core/Dropdown/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Dropdown/DropdownItem/DropdownItem.basestyles.tsx
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/Modal/Modal/Modal.md
  yarn.lock
Labels: bug, dependencies
