Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2021-03, with the labels that each got.

#443 [BugFix] Update vulnerable dependencies
  package.json
  src/utils/AutoId.tsx
  yarn.lock
Labels: bug, dependencies

#444 [Feature] Modal dialog
  .styleguidist/styleguidist.sections.js
  package.json
  src/core/Modal/Modal/Modal.baseStyles.tsx
  src/core/Modal/Modal/Modal.globals.scss
  src/core/Modal/Modal/Modal.md
  src/core/Modal/Modal/Modal.test.tsx
  src/core/Modal/Modal/Modal.tsx
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalContent/ModalContent.baseStyles.tsx
  src/core/Modal/ModalContent/ModalContent.test.tsx
  src/core/Modal/ModalContent/ModalContent.tsx
  src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
  src/core/Modal/ModalFooter/ModalFooter.baseStyles.tsx
  src/core/Modal/ModalFooter/ModalFooter.test.tsx
  src/core/Modal/ModalFooter/ModalFooter.tsx
  src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
  src/core/Modal/ModalTitle/ModalTitle.baseStyles.tsx
  src/core/Modal/ModalTitle/ModalTitle.tsx
  src/core/Modal/index.ts
  src/core/theme/radius.ts
  src/index.tsx
  src/utils/common.ts
  yarn.lock
Labels: enhancement

#445 Fix SSR issue with AutoId.
  src/utils/AutoId.tsx
Labels: bug

#446 [Feature] Button secondary noborder styles and button link variant
  package.json
  src/core/Button/Button.baseStyles.tsx
  src/core/Button/Button.md
  src/core/Button/Button.test.tsx
  src/core/Button/Button.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Colors/__snapshots__/Colors.test.tsx.snap
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
  src/core/theme/colors.ts
  yarn.lock
Labels: dependencies, enhancement

#448 [Bugfix] Link button gradient direction
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
  src/core/theme/colors.ts
Labels: bug

#447 Fix/chip props and styles
  src/core/Chip/BaseChip/BaseChip.baseStyles.tsx
  src/core/Chip/Chip/Chip.baseStyles.tsx
  src/core/Chip/Chip/Chip.md
  src/core/Chip/Chip/Chip.tsx
  src/core/Chip/Chip/__snapshots__/Chip.test.tsx.snap
  src/core/Chip/StaticChip/StaticChip.md
  src/core/Chip/StaticChip/__snapshots__/StaticChip.test.tsx.snap
Labels: bug

#449 [Fix] Remove uuid dependency, type definitions and util
  package.json
  src/utils/uuid.ts
  yarn.lock
Labels: dependencies

#450 [Fix] Modal mouse event issue
  src/core/Modal/Modal/Modal.baseStyles.tsx
  src/core/Modal/Modal/Modal.tsx
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
  src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
  src/reset/HtmlDiv/HtmlDiv.tsx
  src/reset/index.ts
Labels: Accessibility, bug

#451 [Bugfix] Destructure debounce out of TextInput and SearchInput props
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/TextInput/TextInput.tsx
Labels: bug

#454 [Fix] Move Heading to core
  src/components/Heading/Heading.tsx
  src/components/index.ts
  src/core/Heading/Heading.md
  src/core/Heading/Heading.test.tsx
  src/core/Heading/Heading.tsx
  src/core/Modal/ModalTitle/ModalTitle.tsx
  src/reset/index.ts
Labels: DX, bug
