Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2021-10, with the labels that each got.

#503 Feature/select
  .styleguidist/styleguidist.sections.js
  src/core/Chip/ChipList/ChipList.baseStyles.tsx
  src/core/Chip/ChipList/ChipList.tsx
  src/core/Chip/index.ts
  src/core/Form/FilterInput/FilterInput.baseStyles.tsx
  src/core/Form/FilterInput/FilterInput.tsx
  src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap
  src/core/Form/Form.tsx
  src/core/Form/InputClearButton/InputClearButton.baseStyles.ts
  src/core/Form/InputClearButton/InputClearButton.tsx
  src/core/Form/InputToggleButton/InputToggleButton.baseStyles.ts
  src/core/Form/InputToggleButton/InputToggleButton.tsx
  src/core/Form/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/Form/MultiSelect/MultiSelectEmptyItem/MultiSelectEmptyItem.tsx
  src/core/Form/MultiSelect/MultiSelectItem/MultiSelectItem.baseStyles.tsx
  src/core/Form/MultiSelect/MultiSelectItem/MultiSelectItem.tsx
  src/core/Form/MultiSelect/MultiSelectItemList/MultiSelectItemList.baseStyles.tsx
  src/core/Form/MultiSelect/MultiSelectItemList/MultiSelectItemList.tsx
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/Select/BaseSelect/SelectEmptyItem/SelectEmptyItem.baseStyles.tsx
  src/core/Form/Select/BaseSelect/SelectEmptyItem/SelectEmptyItem.tsx
  src/core/Form/Select/BaseSelect/SelectItem/SelectItem.baseStyles.tsx
  src/core/Form/Select/BaseSelect/SelectItem/SelectItem.tsx
  src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.baseStyles.tsx
  src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.baseStyles.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.md
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/Form/Select/MultiSelect/MultiSelectChipList/MultiSelectChipList.tsx
  src/core/Form/Select/MultiSelect/MultiSelectRemoveAllButton/MultiSelectRemoveAllButton.tsx
  src/core/Form/Select/MultiSelect/index.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.baseStyles.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.md
  src/core/Form/Select/SingleSelect/SingleSelect.test.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
  src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  src/core/Form/Select/index.tsx
  src/core/Popover/Popover.tsx
  src/index.tsx
  src/utils/common/common.ts
  src/utils/common/index.ts
Labels: enhancement

#508 [Fix] Dependencies updates
  package.json
  yarn.lock
Labels: dependencies

#509 Fix Input clear button focus position and update snapshots.
  src/core/Form/InputClearButton/InputClearButton.baseStyles.ts
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
Labels: bug

#510 [Release] v6.0.0.
  .styleguidist/styleguidist.sections.js
  package.json
  src/index.tsx
Labels: release

#515 [Fix] documentation related to statics and component level.
  .styleguidist/colors.md
  .styleguidist/introduction.md
  .styleguidist/spacing.md
  .styleguidist/typography.md
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
Labels: enhancement
