Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2021-11, with the labels that each got.

#528 [Feature] Alert component
  .styleguidist/styleguidist.sections.js
  src/core/Alert/Alert/Alert.baseStyles.ts
  src/core/Alert/Alert/Alert.md
  src/core/Alert/Alert/Alert.test.tsx
  src/core/Alert/Alert/Alert.tsx
  src/core/Alert/Alert/__snapshots__/Alert.test.tsx.snap
  src/core/Alert/BaseAlert/BaseAlert.baseStyles.ts
  src/core/Alert/BaseAlert/BaseAlert.tsx
  src/core/Alert/InlineAlert/InlineAlert.baseStyles.ts
  src/core/Alert/InlineAlert/InlineAlert.md
  src/core/Alert/InlineAlert/InlineAlert.test.tsx
  src/core/Alert/InlineAlert/InlineAlert.tsx
  src/core/Alert/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
  src/core/Alert/index.ts
  src/core/theme/SuomifiTheme/gradients.ts
  src/index.tsx
Labels: duplicate, enhancement

#531 [Bugfix] Alert spacing, role, colors and examples
  src/core/Alert/Alert/Alert.baseStyles.ts
  src/core/Alert/Alert/Alert.md
  src/core/Alert/Alert/Alert.test.tsx
  src/core/Alert/Alert/Alert.tsx
  src/core/Alert/Alert/__snapshots__/Alert.test.tsx.snap
  src/core/Alert/BaseAlert/BaseAlert.baseStyles.ts
  src/core/Alert/BaseAlert/BaseAlert.tsx
  src/core/Alert/InlineAlert/InlineAlert.baseStyles.ts
  src/core/Alert/InlineAlert/InlineAlert.md
  src/core/Alert/InlineAlert/InlineAlert.tsx
  src/core/Alert/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
Labels: bug

#532 [Release] v.6.1.0-beta.2
  package.json
Labels: release
