Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2021-01, with the labels that each got.

#422 [Feature] Improve test run speeds
  package.json
Labels: DX

#423 [Fix] Aria attribute issues
  src/core/Breadcrumb/Breadcrumb.tsx
  src/core/Button/Button.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Expander/ExpanderContent/ExpanderContent.tsx
  src/core/Expander/ExpanderGroup/ExpanderGroup.tsx
  src/core/Expander/ExpanderTitle/ExpanderTitle.tsx
  src/core/Expander/ExpanderTitleButton/ExpanderTitleButton.tsx
  src/core/Form/Checkbox/Checkbox.tsx
  src/core/Form/Textarea/Textarea.tsx
  src/utils/aria.test.ts
  src/utils/aria.ts
Labels: Accessibility, bug

#424 [Bugfix] Remove native internet explorer pseudo elements from text input
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: bug

#427 Increase version number to 3.0.0-beta.1
  package.json
Labels: release

#425 [Feature] FilterInput (internal)
  src/core/Form/FilterInput/FilterInput.baseStyles.tsx
  src/core/Form/FilterInput/FilterInput.test.tsx
  src/core/Form/FilterInput/FilterInput.tsx
  src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap
Labels: enhancement

#426 [Bugfix] Box sizing inheritance
  src/core/Block/__snapshots__/Block.test.tsx.snap
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Chip/__snapshots__/Chip.test.tsx.snap
  src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/ExpanderContent/__snapshots__/ExpanderContent.test.tsx.snap
  src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap
  src/core/Expander/ExpanderTitleButton/__snapshots__/ExpanderTitleButton.test.tsx.snap
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap
  src/core/Form/RadioButton/RadioButton.baseStyles.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/Heading/__snapshots__/Heading.test.tsx.snap
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/Link.baseStyles.ts
  src/core/Link/__snapshots__/Link.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/Paragraph/__snapshots__/Paragraph.test.tsx.snap
  src/core/Text/__snapshots__/Text.test.tsx.snap
  src/core/theme/__snapshots__/tokens.test.tsx.snap
  src/reset/utils/index.ts
Labels: bug

#428 [Feature] Move radio button to core
  .styleguidist/styleguidist.sections.js
  src/components/Form/RadioButton.tsx
  src/components/Form/RadioButtonDivider.tsx
  src/components/Form/RadioButtonGroup.tsx
  src/components/index.ts
  src/core/Form/Form.tsx
  src/core/Form/RadioButton/RadioButton.md
  src/core/Form/RadioButton/RadioButton.tsx
  src/core/Form/RadioButton/RadioButtonDivider.baseStyles.tsx
  src/core/Form/RadioButton/RadioButtonDivider.tsx
  src/core/Form/RadioButton/RadioButtonGroup.test.tsx
  src/core/Form/RadioButton/RadioButtonGroup.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/core/Form/RadioButton/index.ts
  src/reset/HtmlFieldSet/HtmlFieldSet.tsx
  src/reset/HtmlLegend/HtmlLegend.tsx
  src/reset/index.ts
Labels: Accessibility, DX

#430 [BugFix] Add resolution for react-styleguidist immer dependency
  package.json
  yarn.lock
Labels: dependencies

#431 [Release] 3.0.0
  package.json
Labels: release
