Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2021-05, with the labels that each got.

#461 [Fix] Form element status accessibility
  src/core/Form/Checkbox/Checkbox.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/FilterInput/FilterInput.tsx
  src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/StatusText/StatusText.baseStyles.tsx
  src/core/Form/StatusText/StatusText.test.tsx
  src/core/Form/StatusText/StatusText.tsx
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/Textarea.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/core/Form/types.ts
  src/utils/aria.ts
Labels: bug

#464 [Dependencies] Update suomifi-design-tokens to 3.1.1
  package.json
  yarn.lock
Labels: dependencies

#465 [Feature] Add aria-atomic to StatusText component
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/StatusText/StatusText.test.tsx
  src/core/Form/StatusText/StatusText.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
Labels: enhancement

#467 [Fix] Modal focus lock portals and React 17 support
  package.json
  src/core/Heading/Heading.tsx
  src/core/Modal/Modal/Modal.baseStyles.tsx
  src/core/Modal/Modal/Modal.md
  src/core/Modal/Modal/Modal.test.tsx
  src/core/Modal/Modal/Modal.tsx
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalContent/ModalContent.test.tsx
  src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
  src/core/Modal/ModalFooter/ModalFooter.test.tsx
  src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
  src/core/Modal/ModalTitle/ModalTitle.baseStyles.tsx
  src/core/Modal/ModalTitle/ModalTitle.tsx
  src/reset/HtmlH/HtmlH.tsx
  src/reset/index.ts
  yarn.lock
Labels: Accessibility, bug, dependencies

#468 [Fix] Update vulnerable dependencies
  package.json
  yarn.lock
Labels: dependencies

#469 [Release] Raise version to 3.0.1
  package.json
Labels: release

#470 [Fix] Update vulnerable dependencies for 4.0.0
  package.json
  yarn.lock
Labels: dependencies
