Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2021-06, with the labels that each got.

#471 [Fix] Component focusability in modal
  src/core/Button/Button.tsx
  src/core/Dropdown/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Expander/ExpanderTitle/ExpanderTitle.baseStyles.tsx
  src/core/Expander/ExpanderTitle/ExpanderTitle.tsx
  src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Modal/Modal/Modal.md
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalContent/ModalContent.baseStyles.tsx
  src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
Labels: Accessibility, bug

#475 [Fix] Bump dns-packet and ws to fix vulnerabilities
  yarn.lock
Labels: dependencies

#473 [Fix] Dropdown tab-key focus issue
  src/core/Dropdown/Dropdown/Dropdown.tsx
Labels: bug

#476 [Feature] Soft disable support for Chip
  src/core/Chip/Chip/Chip.md
  src/core/Chip/Chip/Chip.test.tsx
  src/core/Chip/Chip/Chip.tsx
  src/core/Chip/Chip/__snapshots__/Chip.test.tsx.snap
Labels: enhancement

#477 Set modal aria-modal attribute to false to fix Safari issue.
  src/core/Modal/Modal/Modal.baseStyles.tsx
  src/core/Modal/Modal/Modal.globals.scss
  src/core/Modal/Modal/Modal.md
  src/core/Modal/Modal/Modal.tsx
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
  src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
Labels: Accessibility, bug

#478 [Fix] VisuallyHidden to export props + move it to core
  src/components/Visually-hidden/Visually-hidden.tsx
  src/components/index.ts
  src/core/Chip/Chip/Chip.tsx
  src/core/Expander/ExpanderGroup/ExpanderGroup.tsx
  src/core/Expander/ExpanderTitle/ExpanderTitle.tsx
  src/core/Form/LabelText/LabelText.tsx
  src/core/Form/RadioButton/RadioButtonGroup.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Link/LinkExternal.tsx
  src/core/VisuallyHidden/VisuallyHidden.tsx
  src/index.tsx
Labels: bug, enhancement

#438 [Feature] MultiSelect (Combobox)
  .styleguidist/styleguidist.sections.js
  package.json
  src/core/Form/FilterInput/FilterInput.tsx
  src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap
  src/core/Form/Form.tsx
  src/core/Form/MultiSelect/ChipList/ChipList.baseStyles.tsx
  src/core/Form/MultiSelect/ChipList/ChipList.tsx
  src/core/Form/MultiSelect/MultiSelect/MultiSelect.baseStyles.tsx
  src/core/Form/MultiSelect/MultiSelect/MultiSelect.md
  src/core/Form/MultiSelect/MultiSelect/MultiSelect.test.tsx
  src/core/Form/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/Form/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/Form/MultiSelect/MultiSelectEmptyItem/MultiSelectEmptyItem.baseStyles.tsx
  src/core/Form/MultiSelect/MultiSelectEmptyItem/MultiSelectEmptyItem.tsx
  src/core/Form/MultiSelect/MultiSelectItem/MultiSelectItem.baseStyles.tsx
  src/core/Form/MultiSelect/MultiSelectItem/MultiSelectItem.tsx
  src/core/Form/MultiSelect/MultiSelectItemList/MultiSelectItemList.baseStyles.tsx
  src/core/Form/MultiSelect/MultiSelectItemList/MultiSelectItemList.tsx
  src/core/Form/MultiSelect/index.tsx
  src/core/Popover/Popover.tsx
  src/index.tsx
  src/reset/HtmlUl/HtmlUl.tsx
  src/reset/index.ts
Labels: enhancement

#479 [Fix] MultiSelect not showing up in styleguidist
  .styleguidist/styleguidist.sections.js
Labels: bug

#480 [Feature] Icon color
  package.json
  src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap
  src/core/Expander/ExpanderTitleButton/__snapshots__/ExpanderTitleButton.test.tsx.snap
  src/core/Form/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/Toggle/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap
  src/core/Form/Toggle/ToggleInput/__snapshots__/ToggleInput.test.tsx.snap
  src/core/Icon/Icon.baseStyles.tsx
  src/core/Icon/__snapshots__/Icon.test.tsx.snap
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
  src/core/StaticIcon/StaticIcon.baseStyles.tsx
  src/core/StaticIcon/StaticIcon.md
  src/core/StaticIcon/StaticIcon.tsx
  src/core/StaticIcon/__snapshots__/StaticIcon.test.tsx.snap
  yarn.lock
Labels: dependencies, enhancement

#481 [Release] 4.0.0
  .styleguidist/styleguidist.sections.js
  package.json
  src/index.tsx
Labels: release

#486 [Fix] Destructure baseColor from props in the StaticIcon
  src/core/StaticIcon/StaticIcon.tsx
Labels: bug

#487 [Fix] ToggleInput example
  src/core/Form/Toggle/ToggleButton/ToggleButton.md
Labels: bug
