Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2021-08, with the labels that each got.

#495 [Feature] Remove breadcrumb variant prop
  .styleguidist/styleguidist.sections.js
  src/core/Breadcrumb/Breadcrumb.baseStyles.ts
  src/core/Breadcrumb/Breadcrumb/Breadcrumb.baseStyles.ts
  src/core/Breadcrumb/Breadcrumb/Breadcrumb.md
  src/core/Breadcrumb/Breadcrumb/Breadcrumb.test.tsx
  src/core/Breadcrumb/Breadcrumb/Breadcrumb.tsx
  src/core/Breadcrumb/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Breadcrumb/BreadcrumbLink.tsx
  src/core/Breadcrumb/BreadcrumbLink/BreadcrumbLink.baseStyles.ts
  src/core/Breadcrumb/BreadcrumbLink/BreadcrumbLink.md
  src/core/Breadcrumb/BreadcrumbLink/BreadcrumbLink.tsx
  src/core/Breadcrumb/index.ts
  src/index.tsx
Labels: bug, DX

#494 [Feature] Remove font imports
  .styleguidist/styleguidist.require.js
  README.md
  src/core/theme/fontFaces.css
  src/core/theme/index.ts
  src/reset/utils/index.ts
Labels: enhancement, dependencies

#496 [Fix] MultiSelect adjustments
  src/core/Form/MultiSelect/MultiSelect/AriaAnnounceText.tsx
  src/core/Form/MultiSelect/MultiSelect/MultiSelect.tsx
Labels: enhancement

#497 [Security] Update vulnerable dependencies
  package.json
  yarn.lock
Labels: dependencies
