Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2021-02, with the labels that each got.

#429 [Breaking change] Move Dropdown to core and implement AutoId
  .styleguidist/styleguidist.sections.js
  src/components/Dropdown/Dropdown.tsx
  src/components/index.ts
  src/core/Dropdown/Dropdown.tsx
  src/core/Dropdown/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/Dropdown/Dropdown.md
  src/core/Dropdown/Dropdown/Dropdown.test.tsx
  src/core/Dropdown/Dropdown/Dropdown.tsx
  src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Dropdown/DropdownItem.tsx
  src/core/Dropdown/DropdownItem/DropdownItem.basestyles.tsx
  src/core/Dropdown/DropdownItem/DropdownItem.md
  src/core/Dropdown/DropdownItem/DropdownItem.tsx
  src/core/Dropdown/index.ts
  src/index.tsx
Labels: DX

#432 [Feature] SearchInput auto id
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/SearchInput.md
  src/core/Form/SearchInput/SearchInput.test.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
Labels: DX, enhancement

#435 [BreakingChange] Text input AutoId, aria util and styling
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: DX, enhancement

#434 [Feature] Move toggle to core
  .styleguidist/styleguidist.sections.js
  src/components/Form/Form.tsx
  src/components/Form/Toggle.tsx
  src/components/Form/ToggleButton.tsx
  src/components/Form/ToggleInput.tsx
  src/components/index.ts
  src/core/Form/Form.tsx
  src/core/Form/Toggle/Toggle.baseStyles.tsx
  src/core/Form/Toggle/Toggle.md
  src/core/Form/Toggle/Toggle.test.tsx
  src/core/Form/Toggle/Toggle.tsx
  src/core/Form/Toggle/ToggleBase/Toggle.baseStyles.tsx
  src/core/Form/Toggle/ToggleBase/ToggleBase.tsx
  src/core/Form/Toggle/ToggleBase/ToggleIcon.baseStyles.tsx
  src/core/Form/Toggle/ToggleBase/ToggleIcon.tsx
  src/core/Form/Toggle/ToggleButton/ToggeButton.baseStyles.tsx
  src/core/Form/Toggle/ToggleButton/ToggleButton.md
  src/core/Form/Toggle/ToggleButton/ToggleButton.test.tsx
  src/core/Form/Toggle/ToggleButton/ToggleButton.tsx
  src/core/Form/Toggle/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap
  src/core/Form/Toggle/ToggleInput/ToggleInput.baseStyles.tsx
  src/core/Form/Toggle/ToggleInput/ToggleInput.md
  src/core/Form/Toggle/ToggleInput/ToggleInput.test.tsx
  src/core/Form/Toggle/ToggleInput/ToggleInput.tsx
  src/core/Form/Toggle/ToggleInput/__snapshots__/ToggleInput.test.tsx.snap
  src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/core/Form/Toggle/index.tsx
  src/index.tsx
Labels: DX, enhancement

#436 [Bugfix] Add missing spread operator to TextInput icon props
  src/core/Form/TextInput/TextInput.tsx
Labels: bug

#437 [Feature] Update icons and styles
  package.json
  src/core/Form/RadioButton/RadioButton.baseStyles.tsx
  src/core/Form/RadioButton/RadioButton.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/core/Form/Toggle/ToggleBase/ToggleIcon.baseStyles.tsx
  src/core/Form/Toggle/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap
  src/core/Form/Toggle/ToggleInput/__snapshots__/ToggleInput.test.tsx.snap
  src/core/Icon/Icon.baseStyles.tsx
  src/core/StaticIcon/StaticIcon.md
  src/core/StaticIcon/StaticIcon.tsx
  src/core/StaticIcon/__snapshots__/StaticIcon.test.tsx.snap
  yarn.lock
Labels: bug, enhancement
