Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2021-12, with the labels that each got.

#533 [Fix] Change node-sass to Dart Sass
  package.json
  src/styles.scss
  yarn.lock
Labels: bug, dependencies

#534 [Fix] Design token types exports
  src/core/theme/SuomifiTheme/SuomifiTheme.ts
  src/core/theme/SuomifiTheme/gradients.ts
  src/core/theme/SuomifiTheme/shadows.ts
  src/core/theme/index.ts
  src/core/theme/utils/spacing.ts
  src/index.tsx
Labels: bug

#527 [Feature] Add table of supported OS, browser and screen reader combinations
  README.md
Labels: enhancement

#535 [Release]6.1.0-beta.3
  package.json
Labels: release

#538 [Fix] Update internal aria util
  src/utils/aria/aria.ts
Labels: bug, DX

#530 [Feature] Notification component
  .styleguidist/styleguidist.sections.js
  src/core/Notification/Notification.baseStyles.ts
  src/core/Notification/Notification.md
  src/core/Notification/Notification.test.tsx
  src/core/Notification/Notification.tsx
  src/core/Notification/__snapshots__/Notification.test.tsx.snap
  src/core/theme/SuomifiTheme/shadows.ts
  src/index.tsx
Labels: enhancement
