Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2022-05, with the labels that each got.

#600 [Feature] Make MultiSelect use InputToggleButton
  src/core/Dropdown/DropdownItem/DropdownItem.basestyles.tsx
  src/core/Form/InputToggleButton/InputToggleButton.baseStyles.ts
  src/core/Form/Select/BaseSelect/SelectItem/SelectItem.baseStyles.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.baseStyles.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/Form/Select/SingleSelect/SingleSelect.test.tsx
  src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
Labels: DX

#609 [Fix] Remove background color from Toggle components
  src/core/Form/Toggle/ToggleBase/Toggle.baseStyles.tsx
  src/core/Form/Toggle/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap
  src/core/Form/Toggle/ToggleInput/__snapshots__/ToggleInput.test.tsx.snap
Labels: bug

#618 [Fix] BaseChip styling cleanup
  src/core/Chip/BaseChip/BaseChip.baseStyles.tsx
  src/core/Chip/Chip/__snapshots__/Chip.test.tsx.snap
  src/core/Chip/StaticChip/__snapshots__/StaticChip.test.tsx.snap
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
Labels: bug

#614 [Fix] SingleSelect controlled state bug
  src/core/Form/Select/SingleSelect/SingleSelect.md
  src/core/Form/Select/SingleSelect/SingleSelect.test.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
Labels: bug

#621 [Release] 8.0.0-beta.0
  package.json
Labels: release

#620 [Fix] Update engines field in package.json
  package.json
Labels: DX

#602 [Fix] RadioButton & RadioButtonGroup adjustments
  src/core/Form/RadioButton/RadioButton.baseStyles.tsx
  src/core/Form/RadioButton/RadioButton.md
  src/core/Form/RadioButton/RadioButton.test.tsx
  src/core/Form/RadioButton/RadioButton.tsx
  src/core/Form/RadioButton/RadioButtonGroup.baseStyles.tsx
  src/core/Form/RadioButton/RadioButtonGroup.test.tsx
  src/core/Form/RadioButton/RadioButtonGroup.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
Labels: enhancement

#623 [Fix] API documentation styling
  .styleguidist/styleguidist.styles.js
Labels: DX

#622 [Fix] ExternalLink new window props
  src/core/Link/ExternalLink/ExternalLink.tsx
  src/core/Link/Link/Link.md
Labels: bug
