Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2022-10, with the labels that each got.

#656 [Feature] WizardNavigation
  .styleguidist/styleguidist.sections.js
  src/core/Navigation/WizardNavigation/WizardNavigation/WizardNavigation.baseStyles.tsx
  src/core/Navigation/WizardNavigation/WizardNavigation/WizardNavigation.md
  src/core/Navigation/WizardNavigation/WizardNavigation/WizardNavigation.test.tsx
  src/core/Navigation/WizardNavigation/WizardNavigation/WizardNavigation.tsx
  src/core/Navigation/WizardNavigation/WizardNavigation/__snapshots__/WizardNavigation.test.tsx.snap
  src/core/Navigation/WizardNavigation/WizardNavigationItem/WizardNavigationItem.baseStyles.tsx
  src/core/Navigation/WizardNavigation/WizardNavigationItem/WizardNavigationItem.md
  src/core/Navigation/WizardNavigation/WizardNavigationItem/WizardNavigationItem.tsx
  src/core/Navigation/WizardNavigation/index.ts
  src/index.tsx
  src/reset/HtmlNav/HtmlNav.tsx
Labels: new-component

#651 [Feature] ServiceNavigation
  .styleguidist/styleguidist.sections.js
  src/core/Navigation/ServiceNavigation/ServiceNavigation/ServiceNavigation.baseStyles.tsx
  src/core/Navigation/ServiceNavigation/ServiceNavigation/ServiceNavigation.md
  src/core/Navigation/ServiceNavigation/ServiceNavigation/ServiceNavigation.test.tsx
  src/core/Navigation/ServiceNavigation/ServiceNavigation/ServiceNavigation.tsx
  src/core/Navigation/ServiceNavigation/ServiceNavigation/__snapshots__/ServiceNavigation.test.tsx.snap
  src/core/Navigation/ServiceNavigation/ServiceNavigationItem/ServiceNavigationItem.baseStyles.tsx
  src/core/Navigation/ServiceNavigation/ServiceNavigationItem/ServiceNavigationItem.md
  src/core/Navigation/ServiceNavigation/ServiceNavigationItem/ServiceNavigationItem.tsx
  src/core/Navigation/ServiceNavigation/index.ts
  src/index.tsx
Labels: new-component

#662 [Feature] Ref to RouterLink
  src/core/Link/Link/Link.md
  src/core/Link/RouterLink/RouterLink.tsx
Labels: enhancement

#666 [Release] 9.1.0-beta.1
  package.json
Labels: release

#665 [Feature] Link underline option
  src/core/Breadcrumb/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Link/BaseLink/BaseLink.baseStyles.ts
  src/core/Link/BaseLink/BaseLink.tsx
  src/core/Link/ExternalLink/ExternalLink.tsx
  src/core/Link/ExternalLink/__snapshots__/ExternalLink.test.tsx.snap
  src/core/Link/Link/Link.md
  src/core/Link/Link/Link.test.tsx
  src/core/Link/Link/Link.tsx
  src/core/Link/Link/__snapshots__/Link.test.tsx.snap
  src/core/Link/RouterLink/RouterLink.baseStyles.ts
  src/core/Link/RouterLink/RouterLink.test.tsx
  src/core/Link/RouterLink/RouterLink.tsx
  src/core/Link/RouterLink/__snapshots__/RouterLink.test.tsx.snap
  src/core/Link/SkipLink/SkipLink.baseStyles.ts
  src/core/Link/SkipLink/__snapshots__/SkipLink.test.tsx.snap
  src/core/Navigation/ServiceNavigation/ServiceNavigation/__snapshots__/ServiceNavigation.test.tsx.snap
  src/core/Navigation/WizardNavigation/WizardNavigation/__snapshots__/WizardNavigation.test.tsx.snap
Labels: Accessibility
