Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2022-01, with the labels that each got.

#542 [fix] Remove from utils. Removed unused CSS code
  src/utils/css/utils.ts
Labels: DX

#536 [Fix] SingleSelect accessibility improvements
  src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.baseStyles.tsx
  src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.test.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
  src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  src/reset/HtmlSpan/HtmlSpan.tsx
  src/reset/index.ts
Labels: bug

#537 [Fix] Multiselect accessibility fixes
  src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/reset/HtmlSpan/HtmlSpan.tsx
  src/reset/index.ts
Labels: bug

#546 [Release] v6.1.0
  package.json
Labels: release

#548 [Release] Merge develop 6.1.0 to master
  .github/CODEOWNERS
  .styleguidist/styleguidist.sections.js
  README.md
  package.json
  src/core/Alert/Alert/Alert.baseStyles.ts
  src/core/Alert/Alert/Alert.md
  src/core/Alert/Alert/Alert.test.tsx
  src/core/Alert/Alert/Alert.tsx
  src/core/Alert/Alert/__snapshots__/Alert.test.tsx.snap
  src/core/Alert/BaseAlert/BaseAlert.baseStyles.ts
  src/core/Alert/BaseAlert/BaseAlert.tsx
  src/core/Alert/InlineAlert/InlineAlert.baseStyles.ts
  src/core/Alert/InlineAlert/InlineAlert.md
  src/core/Alert/InlineAlert/InlineAlert.test.tsx
  src/core/Alert/InlineAlert/InlineAlert.tsx
  src/core/Alert/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
  src/core/Alert/index.ts
  src/core/Dropdown/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/Dropdown/Dropdown.md
  src/core/Dropdown/Dropdown/Dropdown.tsx
  src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.baseStyles.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/Form/Select/SingleSelect/SingleSelect.test.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
  src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  src/core/Icon/Icon.md
  src/core/Notification/Notification.baseStyles.ts
  src/core/Notification/Notification.md
  src/core/Notification/Notification.test.tsx
  src/core/Notification/Notification.tsx
  src/core/Notification/__snapshots__/Notification.test.tsx.snap
  src/core/StaticIcon/StaticIcon.md
  src/core/theme/SuomifiTheme/SuomifiTheme.ts
  src/core/theme/SuomifiTheme/gradients.ts
  src/core/theme/SuomifiTheme/shadows.ts
  src/core/theme/index.ts
  src/core/theme/utils/spacing.ts
  src/index.tsx
  src/styles.scss
  src/utils/aria/aria.ts
  src/utils/css/utils.ts
  tsdx.config.js
  yarn.lock
Labels: release

#550 [Fix] Single- and Multiselect regexp escape
  src/core/Form/Select/BaseSelect/SelectItem/SelectItem.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
  src/utils/common/common.ts
  src/utils/common/index.ts
Labels: bug

#551 [Release] Increase version number to 6.1.1-beta.0
  package.json
Labels: release

#552 [Release] 6.1.1
  package.json
Labels: release

#553 [Release] Merge develop 6.1.1 to master
  package.json
  src/core/Form/Select/BaseSelect/SelectItem/SelectItem.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
  src/utils/common/common.ts
  src/utils/common/index.ts
Labels: release

#524 [Feature] Use rollup for build
  .eslintrc
  .stylelintrc
  jest.config.js
  jest/jest.setup.js
  jest/jest.transformer.js
  jest/jest.transformer.stub.js
  package.json
  rollup.config.js
  src/core/Alert/Alert/Alert.tsx
  src/core/Alert/Alert/__snapshots__/Alert.test.tsx.snap
  src/core/Alert/InlineAlert/InlineAlert.tsx
  src/core/Alert/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
  src/core/Block/Block.tsx
  src/core/Breadcrumb/Breadcrumb/Breadcrumb.tsx
  src/core/Breadcrumb/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Button/Button.tsx
  src/core/Chip/StaticChip/StaticChip.baseStyles.tsx
  src/core/Expander/Expander/Expander.tsx
  src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/ExpanderContent/ExpanderContent.tsx
  src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap
  src/core/Expander/ExpanderTitleButton/__snapshots__/ExpanderTitleButton.test.tsx.snap
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/Checkbox.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
  src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  src/core/Form/index.ts
  src/core/Icon/__snapshots__/Icon.test.tsx.snap
  src/core/LanguageMenu/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/BaseLink/BaseLink.baseStyles.ts
  src/core/Link/ExternalLink/ExternalLink.tsx
  src/core/Link/ExternalLink/__snapshots__/ExternalLink.test.tsx.snap
  src/core/Link/Link/Link.tsx
  src/core/Notification/Notification.tsx
  src/core/Notification/__snapshots__/Notification.test.tsx.snap
  src/core/StaticIcon/StaticIcon.baseStyles.tsx
  src/core/Text/Text.tsx
  src/docs/Colors/Colors.tsx
  src/docs/Theme/ThemeProps.tsx
  src/index.tsx
  tsconfig.json
  tsdx.config.js
  yarn.lock
Labels: enhancement, DX, dependencies

#539 [Feature] Export inner form components
  .styleguidist/styleguidist.sections.js
  src/core/Dropdown/Dropdown/Dropdown.tsx
  src/core/Form/FilterInput/FilterInput.tsx
  src/core/Form/HintText/HintText.md
  src/core/Form/Label/Label.baseStyles.tsx
  src/core/Form/Label/Label.md
  src/core/Form/Label/Label.test.tsx
  src/core/Form/Label/Label.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/StatusText/StatusText.md
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/Textarea/Textarea.tsx
  src/core/Form/index.ts
  src/index.tsx
Labels: enhancement
