Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2022-03, with the labels that each got.

#574 [Release] Increase version number to 6.2.1
  package.json
Labels: release

#575 [Release] Merge develop 6.2.1 to master
  package.json
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/LanguageMenu/LanguageMenu/LanguageMenu.tsx
Labels: release

#563 [Fix/Feature] Change using of env variables to logger util
  .styleguidist/logger.md
  .styleguidist/styleguidist.sections.js
  src/core/Chip/Chip/Chip.tsx
  src/core/Dropdown/Dropdown/Dropdown.tsx
  src/core/Form/Checkbox/Checkbox.tsx
  src/core/Form/RadioButton/RadioButton.tsx
  src/core/Heading/Heading.tsx
  src/core/Icon/Icon.tsx
  src/core/LanguageMenu/LanguageMenu/LanguageMenu.tsx
  src/core/Link/ExternalLink/ExternalLink.tsx
  src/core/Modal/Modal/Modal.tsx
  src/index.tsx
  src/utils/css/colors.ts
  src/utils/log/index.ts
  src/utils/log/logger.ts
Labels: bug, enhancement

#564 [Fix] Fixed width layout for Alert
  src/core/Alert/Alert/Alert.baseStyles.ts
  src/core/Alert/Alert/Alert.tsx
  src/core/Alert/Alert/__snapshots__/Alert.test.tsx.snap
  src/core/Alert/BaseAlert/BaseAlert.baseStyles.ts
  src/core/Alert/BaseAlert/BaseAlert.tsx
  src/core/Alert/InlineAlert/InlineAlert.baseStyles.ts
  src/core/Alert/InlineAlert/InlineAlert.tsx
  src/core/Alert/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
Labels: enhancement

#579 Clarify onItemSelectionsChange prop documentation
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
Labels: bug

#576 [fix]: Remove css from top wrappers
  src/core/Alert/Alert/__snapshots__/Alert.test.tsx.snap
  src/core/Breadcrumb/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Breadcrumb/BreadcrumbLink/BreadcrumbLink.baseStyles.ts
  src/core/Button/Button.baseStyles.tsx
  src/core/Chip/BaseChip/BaseChip.baseStyles.tsx
  src/core/Chip/Chip/__snapshots__/Chip.test.tsx.snap
  src/core/Chip/ChipList/ChipList.baseStyles.tsx
  src/core/Chip/StaticChip/__snapshots__/StaticChip.test.tsx.snap
  src/core/Dropdown/Dropdown/Dropdown.baseStyles.tsx
  src/core/Expander/Expander/Expander.baseStyles.tsx
  src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/ExpanderContent/ExpanderContent.baseStyles.tsx
  src/core/Expander/ExpanderContent/__snapshots__/ExpanderContent.test.tsx.snap
  src/core/Expander/ExpanderGroup/ExpanderGroup.baseStyles.tsx
  src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Expander/ExpanderTitle/ExpanderTitle.baseStyles.tsx
  src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap
  src/core/Expander/ExpanderTitleButton/ExpanderTitleButton.baseStyles.tsx
  src/core/Expander/ExpanderTitleButton/__snapshots__/ExpanderTitleButton.test.tsx.snap
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/FilterInput/FilterInput.baseStyles.tsx
  src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap
  src/core/Form/HintText/HintText.baseStyles.tsx
  src/core/Form/InputClearButton/InputClearButton.baseStyles.ts
  src/core/Form/InputToggleButton/InputToggleButton.baseStyles.ts
  src/core/Form/RadioButton/RadioButton.baseStyles.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/Select/BaseSelect/SelectEmptyItem/SelectEmptyItem.baseStyles.tsx
  src/core/Form/Select/BaseSelect/SelectItem/SelectItem.baseStyles.tsx
  src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.baseStyles.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.baseStyles.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/Form/Select/SingleSelect/SingleSelect.baseStyles.tsx
  src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  src/core/Form/StatusText/StatusText.baseStyles.tsx
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/Textarea.baseStyles.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/core/Form/Toggle/ToggleBase/Toggle.baseStyles.tsx
  src/core/Form/Toggle/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap
  src/core/Form/Toggle/ToggleInput/__snapshots__/ToggleInput.test.tsx.snap
  src/core/Icon/Icon.baseStyles.tsx
  src/core/Icon/__snapshots__/Icon.test.tsx.snap
  src/core/LanguageMenu/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/Link/ExternalLink/__snapshots__/ExternalLink.test.tsx.snap
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
  src/core/Modal/ModalTitle/ModalTitle.baseStyles.tsx
  src/core/Notification/__snapshots__/Notification.test.tsx.snap
  src/core/StaticIcon/StaticIcon.baseStyles.tsx
  src/core/StaticIcon/__snapshots__/StaticIcon.test.tsx.snap
  src/core/Toast/__snapshots__/Toast.test.tsx.snap
Labels: bug, enhancement

#581 [Fix] Update vulnerable dependencies
  package.json
  yarn.lock
Labels: dependencies

#580 [Fix] SingleSelect. Open list by clicking field
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
Labels: bug

#582 [Fix] External link's screen reader text and asProp
  src/core/Link/ExternalLink/ExternalLink.tsx
  src/core/Link/Link/Link.md
Labels: bug

#585 [Release] 7.0.0-beta.0
  package.json
Labels: release

#586 [Fix] SingleSelect async support
  src/core/Form/FilterInput/FilterInput.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
Labels: bug

#584 [Fix] Upgrade dependencies and do migrations
  .styleguidist/webpack.config.js
  .stylelintrc
  package.json
  yarn.lock
Labels: dependencies

#583 [Feature] Multiline chips
  src/core/Chip/BaseChip/BaseChip.baseStyles.tsx
  src/core/Chip/Chip/Chip.baseStyles.tsx
  src/core/Chip/Chip/Chip.md
  src/core/Chip/Chip/__snapshots__/Chip.test.tsx.snap
  src/core/Chip/StaticChip/StaticChip.md
  src/core/Chip/StaticChip/__snapshots__/StaticChip.test.tsx.snap
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
Labels: enhancement

#590 [Fix] Small typo in README about variant example.
  README.md
Labels: bug

#592 [Release] 7.0.0-beta.1
  package.json
Labels: release

#587 [Fix] Notification button styles and structure
  src/core/Notification/Notification.baseStyles.ts
  src/core/Notification/Notification.tsx
  src/core/Notification/__snapshots__/Notification.test.tsx.snap
Labels: bug

#589 [Fix] StaticChip property extension
  src/core/Chip/StaticChip/StaticChip.tsx
Labels: bug
