Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2022-02, with the labels that each got.

#555 [Fix] Align inner form component styles
  src/core/Dropdown/Dropdown/Dropdown.baseStyles.tsx
  src/core/Dropdown/Dropdown/Dropdown.tsx
  src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/Checkbox.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/FilterInput/FilterInput.baseStyles.tsx
  src/core/Form/FilterInput/FilterInput.tsx
  src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap
  src/core/Form/HintText/HintText.baseStyles.tsx
  src/core/Form/HintText/HintText.md
  src/core/Form/Label/Label.baseStyles.tsx
  src/core/Form/Label/Label.md
  src/core/Form/SearchInput/SearchInput.baseStyles.tsx
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  src/core/Form/StatusText/StatusText.baseStyles.tsx
  src/core/Form/StatusText/StatusText.md
  src/core/Form/StatusText/StatusText.tsx
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/Textarea.baseStyles.tsx
  src/core/Form/Textarea/Textarea.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
Labels: bug, enhancement, Accessibility

#541 [Fix] Notification layout
  .styleguidist/styleguidist.sections.js
  src/core/Notification/Notification.baseStyles.ts
  src/core/Notification/Notification.md
  src/core/Notification/Notification.tsx
  src/core/Notification/__snapshots__/Notification.test.tsx.snap
  src/index.tsx
Labels: bug

#559 [Release] Increase version number to 6.2.0-beta.0
  package.json
Labels: release

#554 [Feature] Toast component
  .styleguidist/styleguidist.sections.js
  src/core/Toast/Toast.baseStyles.tsx
  src/core/Toast/Toast.md
  src/core/Toast/Toast.test.tsx
  src/core/Toast/Toast.tsx
  src/core/Toast/__snapshots__/Toast.test.tsx.snap
  src/index.tsx
Labels: enhancement

#558 [Dependency] Upgrade suomifi-design-tokens to 3.2.0
  package.json
  src/core/Alert/Alert/__snapshots__/Alert.test.tsx.snap
  src/core/Alert/BaseAlert/BaseAlert.baseStyles.ts
  src/core/Alert/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
  src/docs/Colors/Colors.tsx
  yarn.lock
Labels: dependencies

#565 [Fix] Update codeowners
  .github/CODEOWNERS
Labels: bug

#557 [Fix] MultiSelect's controlled state should now filter also after selection
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
Labels: bug

#561 [Fix] Modal text styles
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalContent/ModalContent.baseStyles.tsx
  src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
Labels: bug

#566 [Release] Increase version number to 6.2.0-beta.2
  package.json
Labels: release

#569 [Release] Increase version number to 6.2.0
  package.json
Labels: release

#567 [Fix] Duplicate div was removed from LanguageMenu
  src/core/LanguageMenu/LanguageMenu/LanguageMenu.tsx
Labels: bug

#571 [Fix] MultiSelect's item selection in non-controlled state
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
Labels: bug
