Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2022-06, with the labels that each got.

#628 [Release] 8.0.0-beta.1
  package.json
Labels: release

#630 [Release] Increase version number to 8.0.0
  package.json
Labels: release

#631 [Release] 8.0.0
  .github/CODEOWNERS
  .styleguidist/ComponentsList.tsx
  .styleguidist/modules.md
  .styleguidist/primitive.md
  .styleguidist/styleguidist.sections.js
  .styleguidist/styleguidist.styles.js
  package.json
  src/core/Breadcrumb/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/core/Chip/BaseChip/BaseChip.baseStyles.tsx
  src/core/Chip/Chip/__snapshots__/Chip.test.tsx.snap
  src/core/Chip/StaticChip/__snapshots__/StaticChip.test.tsx.snap
  src/core/Dropdown/DropdownItem/DropdownItem.basestyles.tsx
  src/core/Expander/ExpanderGroup/ExpanderGroup.baseStyles.tsx
  src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap
  src/core/Form/FilterInput/FilterInput.baseStyles.tsx
  src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap
  src/core/Form/InputClearButton/InputClearButton.baseStyles.ts
  src/core/Form/InputToggleButton/InputToggleButton.baseStyles.ts
  src/core/Form/RadioButton/RadioButton.baseStyles.tsx
  src/core/Form/RadioButton/RadioButton.md
  src/core/Form/RadioButton/RadioButton.test.tsx
  src/core/Form/RadioButton/RadioButton.tsx
  src/core/Form/RadioButton/RadioButtonGroup.baseStyles.tsx
  src/core/Form/RadioButton/RadioButtonGroup.test.tsx
  src/core/Form/RadioButton/RadioButtonGroup.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/Select/BaseSelect/SelectItem/SelectItem.baseStyles.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.baseStyles.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.md
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/Form/Select/SingleSelect/SingleSelect.md
  src/core/Form/Select/SingleSelect/SingleSelect.test.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
  src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  src/core/Form/Toggle/ToggleBase/Toggle.baseStyles.tsx
  src/core/Form/Toggle/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap
  src/core/Form/Toggle/ToggleInput/__snapshots__/ToggleInput.test.tsx.snap
  src/core/Link/BaseLink/BaseLink.baseStyles.ts
  src/core/Link/ExternalLink/ExternalLink.tsx
  src/core/Link/ExternalLink/__snapshots__/ExternalLink.test.tsx.snap
  src/core/Link/Link/Link.baseStyles.ts
  src/core/Link/Link/Link.md
  src/core/Link/Link/Link.tsx
  src/core/Link/Link/__snapshots__/Link.test.tsx.snap
  src/core/Link/SkipLink/__snapshots__/SkipLink.test.tsx.snap
  suomifi-ui-components.png
  yarn.lock
Labels: release

#596 [Feature] Tooltip
  .styleguidist/styleguidist.sections.js
  jest/jest.setup.js
  src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
  src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap
  src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap
  src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap
  src/core/Form/Label/Label.baseStyles.tsx
  src/core/Form/Label/Label.md
  src/core/Form/Label/Label.test.tsx
  src/core/Form/Label/Label.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/core/Form/SearchInput/SearchInput.test.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/core/Tooltip/Tooltip.md
  src/core/Tooltip/Tooltip.test.tsx
  src/core/Tooltip/Tooltip.tsx
  src/core/Tooltip/TooltipContent/TooltipContent.baseStyles.tsx
  src/core/Tooltip/TooltipContent/TooltipContent.tsx
  src/core/Tooltip/TooltipToggleButton/TooltipToggleButton.baseStyles.tsx
  src/core/Tooltip/TooltipToggleButton/TooltipToggleButton.tsx
  src/core/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  src/index.tsx
  src/reset/HtmlDiv/HtmlDiv.tsx
  src/utils/common/common.ts
  src/utils/common/index.ts
Labels: enhancement

#617 [Fix] Notification accessibility
  src/core/Notification/Notification.baseStyles.ts
  src/core/Notification/Notification.md
  src/core/Notification/Notification.test.tsx
  src/core/Notification/Notification.tsx
  src/core/Notification/__snapshots__/Notification.test.tsx.snap
Labels: Accessibility

#624 [Feature] CheckboxGroup status & status text
  src/core/Form/Checkbox/Checkbox.md
  src/core/Form/Checkbox/Checkbox.tsx
  src/core/Form/Checkbox/CheckboxGroup.test.tsx
  src/core/Form/Checkbox/CheckboxGroup.tsx
  src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap
Labels: enhancement

#629 [Fix] Adjust label classnames
  src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap
  src/core/Form/FilterInput/FilterInput.baseStyles.tsx
  src/core/Form/FilterInput/FilterInput.test.tsx
  src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap
  src/core/Form/Label/Label.baseStyles.tsx
  src/core/Form/Label/Label.test.tsx
  src/core/Form/Label/Label.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
  src/core/Form/SearchInput/SearchInput.test.tsx
  src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/Textarea.test.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
Labels: DX

#633 [Release] 9.0.0-beta.0
  package.json
Labels: release

#626 |Feature] Possibility to add an item outside of list to SingleSelect & MultiSelect
  src/core/Form/Select/BaseSelect/SelectItemAddition/SelectItemAddition.baseStyles.tsx
  src/core/Form/Select/BaseSelect/SelectItemAddition/SelectItemAddition.tsx
  src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.md
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.md
  src/core/Form/Select/SingleSelect/SingleSelect.test.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
Labels: enhancement

#635 [Fix] Tooltip arrow borders
  src/core/Tooltip/Tooltip.tsx
  src/core/Tooltip/TooltipContent/TooltipContent.baseStyles.tsx
Labels: bug

#637 [Release] 9.0.0-beta.1
  package.json
Labels: release

#634 [Feature] Add polymorphic RouterLink component
  .styleguidist/styleguidist.sections.js
  src/core/Link/Link/Link.md
  src/core/Link/RouterLink/RouterLink.baseStyles.ts
  src/core/Link/RouterLink/RouterLink.md
  src/core/Link/RouterLink/RouterLink.test.tsx
  src/core/Link/RouterLink/RouterLink.tsx
  src/core/Link/RouterLink/__snapshots__/RouterLink.test.tsx.snap
  src/core/Link/index.ts
  src/index.tsx
Labels: enhancement

#636 [Fix] Improve typings for MouseEvent and KeyboardEvent
  src/core/Button/Button.tsx
  src/core/Dropdown/Dropdown/Dropdown.tsx
  src/core/Form/Select/BaseSelect/SelectItem/SelectItem.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
  src/core/Tooltip/Tooltip.tsx
  src/core/Tooltip/TooltipContent/TooltipContent.tsx
Labels: bug

#640 [Hotfix] Keyboard event propagation (from master)
  src/core/Dropdown/Dropdown/Dropdown.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
  src/core/LanguageMenu/LanguageMenu/LanguageMenu.tsx
Labels: bug

#642 Update suomifi-icons dependency
  package.json
  yarn.lock
Labels: dependencies
