Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2022-04, with the labels that each got.

#594 [Feature] Disable coverage collection fo Jest
  jest.config.js
Labels: DX

#593 [Feature] CheckboxGroup component
  .styleguidist/styleguidist.sections.js
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/Checkbox.md
  src/core/Form/Checkbox/CheckboxGroup.baseStyles.tsx
  src/core/Form/Checkbox/CheckboxGroup.md
  src/core/Form/Checkbox/CheckboxGroup.test.tsx
  src/core/Form/Checkbox/CheckboxGroup.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap
  src/core/Form/index.ts
  src/index.tsx
Labels: enhancement

#595 [Fix] Toast, Notification and Textarea background color
  src/core/Form/Textarea/Textarea.baseStyles.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
  src/core/Notification/Notification.baseStyles.ts
  src/core/Notification/__snapshots__/Notification.test.tsx.snap
  src/core/Toast/Toast.baseStyles.tsx
  src/core/Toast/__snapshots__/Toast.test.tsx.snap
Labels: bug

#598 [Fix] Update babel-plugin-styled-components to 2.0.7
  package.json
  yarn.lock
Labels: bug

#601 [Release] Increase version number to 7.0.0-beta.2
  package.json
Labels: release

#605 [Release] Change version number to 7.0.0
  package.json
Labels: release
