Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2023-07, with the labels that each got.

#751 [Fix] Styleguidist introduction revamp
  .styleguidist/foundations.md
  .styleguidist/icon.md
  .styleguidist/introduction.md
  .styleguidist/styleguidist.sections.js
  .styleguidist/theme.md
  README.md
Labels: enhancement

#752 [Feature] Character counter for TextInput and Textarea
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/TextInput.md
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/Textarea.baseStyles.tsx
  src/core/Form/Textarea/Textarea.md
  src/core/Form/Textarea/Textarea.test.tsx
  src/core/Form/Textarea/Textarea.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
Labels: enhancement

#753 [Feature] SingleSelect/MultiSelect: Additional props for data-attributes
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.test.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
Labels: enhancement

#754 [Fix] CharacterCounter component tests
  src/core/Form/TextInput/TextInput.test.tsx
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/Textarea/Textarea.test.tsx
  src/core/Form/Textarea/Textarea.tsx
Labels: bug

#756 [Release] 12.0.0-beta.1
  package.json
Labels: release
