Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2023-10, with the labels that each got.

#789 [Release] 13.0.0-beta.0
  package.json
Labels: release

#790 [Hotfix] Alert and InlineAlert refs
  package.json
  src/core/Alert/Alert.tsx
  src/core/InlineAlert/InlineAlert.tsx
Labels: bug

#793 [Fix] Modal fullscreen padding
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalContent/ModalContent.baseStyles.tsx
  src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
  src/core/Modal/ModalFooter/ModalFooter.baseStyles.tsx
  src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
Labels: enhancement
