Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2023-05, with the labels that each got.

#715 [Release] 10.0.0
  package.json
Labels: release

#718 [Release] 10.0.1
  package.json
Labels: release

#719 [Release] 10.0.1
  package.json
  src/core/Dropdown/Dropdown/Dropdown.tsx
  src/core/Dropdown/DropdownItem/DropdownItem.tsx
  src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.tsx
Labels: release

#723 [Release] 10.0.2
  package.json
Labels: release

#724 [Release] 10.0.2
  package.json
  src/core/Dropdown/Dropdown/Dropdown.tsx
Labels: release

#726 [Feature] Documentation versioning
  .gitignore
  .styleguidist/StyleGuideRenderer.tsx
  .styleguidist/styleguidist.sections.js
  .styleguidist/versions.md
  .styleguidist/webpack.config.js
  package.json
  styleguide.add.version.js
  styleguide.config.js
  styleguide.move.build.js
  styleguide.versions.json
  yarn.lock
Labels: enhancement

#731 [Fix] Pagination page number input verification
  src/core/Pagination/PageInput/PageInput.tsx
Labels: bug

#733 [Release] 10.0.3
  .gitignore
  .styleguidist/StyleGuideRenderer.tsx
  .styleguidist/styleguidist.sections.js
  .styleguidist/versions.md
  .styleguidist/webpack.config.js
  package.json
  src/core/Dropdown/Dropdown/Dropdown.tsx
  src/core/Pagination/PageInput/PageInput.tsx
  src/utils/common/common.ts
  styleguide.add.version.js
  styleguide.config.js
  styleguide.move.build.js
  styleguide.versions.json
  yarn.lock
Labels: release

#740 [Release] 10.0.4
  package.json
  src/core/Dropdown/Dropdown/Dropdown.test.tsx
  src/core/Dropdown/Dropdown/Dropdown.tsx
  src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap
  src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.tsx
Labels: release
