Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2023-06, with the labels that each got.

#746 [Release] 11.0.0
  package.json
  src/core/Button/Button.md
Labels: release

#749 [Bugfix] LinkList ariaDescribedBy prop handling
  src/core/Link/LinkList/LinkList.tsx
  src/core/Link/LinkList/__snapshots__/LinkList.test.tsx.snap
Labels: bug

#722 [Feature] LanguageMenu without Reach
  .styleguidist/styleguidist.require.js
  README.md
  package.json
  rollup.config.js
  src/core/Form/DateInput/DateInput.test.tsx
  src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
  src/core/LanguageMenu/LanguageMenu.md
  src/core/LanguageMenu/LanguageMenu.test.tsx
  src/core/LanguageMenu/LanguageMenu.tsx
  src/core/LanguageMenu/LanguageMenu/LanguageMenu.baseStyles.tsx
  src/core/LanguageMenu/LanguageMenu/LanguageMenu.md
  src/core/LanguageMenu/LanguageMenu/LanguageMenu.test.tsx
  src/core/LanguageMenu/LanguageMenu/LanguageMenu.tsx
  src/core/LanguageMenu/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/LanguageMenu/LanguageMenu/index.tsx
  src/core/LanguageMenu/LanguageMenuItem/LanguageMenuItem.baseStyles.tsx
  src/core/LanguageMenu/LanguageMenuItem/LanguageMenuItem.tsx
  src/core/LanguageMenu/LanguageMenuItem/index.tsx
  src/core/LanguageMenu/LanguageMenuLink/LanguageMenuLink.md
  src/core/LanguageMenu/LanguageMenuLink/LanguageMenuLink.tsx
  src/core/LanguageMenu/LanguageMenuLink/index.tsx
  src/core/LanguageMenu/LanguageMenuPopover/LanguageMenuPopover.baseStyles.tsx
  src/core/LanguageMenu/LanguageMenuPopover/LanguageMenuPopover.tsx
  src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
  src/core/LanguageMenu/index.tsx
  src/index.tsx
  src/styles.scss
  yarn.lock
Labels: enhancement
