Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2024-03, with the labels that each got.

#830 [Bugfix] Block spacing props to CSS
  src/core/Block/Block.baseStyles.ts
  src/core/Block/Block.test.tsx
  src/core/Block/Block.tsx
  src/core/Block/__snapshots__/Block.test.tsx.snap
  src/core/theme/utils/spacing.ts
Labels: bug

#833 [Bugfix] Remove Tooltip anchorElement prop from DOM
  src/core/Tooltip/Tooltip.tsx
Labels: bug

#834 [Bugfix] Remove aria-expanded from ExpanderGroup open/close all button
  src/core/Expander/ExpanderGroup/ExpanderGroup.tsx
  src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
Labels: Accessibility

#831 [Bugfix] LinkListItem icon redundant color prop
  src/core/Link/LinkList/__snapshots__/LinkList.test.tsx.snap
  src/core/Link/LinkListItem/LinkListItem.tsx
Labels: bug

#832 [Feature] Loading spinner in button
  src/core/ActionMenu/ActionMenu.tsx
  src/core/ActionMenu/__snapshots__/ActionMenu.test.tsx.snap
  src/core/Button/Button.baseStyles.tsx
  src/core/Button/Button.md
  src/core/Button/Button.test.tsx
  src/core/Button/Button.tsx
  src/core/Button/__snapshots__/Button.test.tsx.snap
  src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/LoadingSpinner/LoadingSpinner.baseStyles.tsx
  src/core/LoadingSpinner/__snapshots__/LoadingSpinner.test.tsx.snap
  src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
  src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
  src/core/Notification/Notification.tsx
  src/core/Notification/__snapshots__/Notification.test.tsx.snap
  src/core/Pagination/__snapshots__/Pagination.test.tsx.snap
Labels: enhancement

#836 [Feature] Add type exports
  src/core/Form/TextInput/TextInput.tsx
  src/core/Form/index.ts
  src/core/theme/index.ts
  src/index.tsx
Labels: enhancement

#835 [Bugfix] TextInput and Textarea spacings
  src/core/Form/TextInput/TextInput.baseStyles.tsx
  src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/core/Form/Textarea/Textarea.baseStyles.tsx
  src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
Labels: bug

#837 [Bugfix] Disabled checkbox icon visibility
  src/core/Form/Checkbox/Checkbox.tsx
Labels: bug

#840 [Bugfix] Empty StatusText icon render
  src/core/Form/StatusText/StatusText.tsx
Labels: bug

#841 [Fix] Dropdown selected value when children change (case language change)
  src/core/Dropdown/Dropdown/Dropdown.tsx
Labels: bug

#845 [Fix] Disabled checkbox hint text color
  src/core/Form/Checkbox/Checkbox.baseStyles.tsx
  src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap
Labels: bug

#844 [Feature] datePickerProps
  src/core/Form/DateInput/DateInput.test.tsx
  src/core/Form/DateInput/DateInput.tsx
  src/core/Form/DateInput/DatePicker/DatePicker.tsx
Labels: enhancement
