Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2024-06, with the labels that each got.

#859 [Feature] SingleSelect and MultiSelect fullWidth prop
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.baseStyles.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.md
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
  src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/core/Form/Select/SingleSelect/SingleSelect.baseStyles.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.md
  src/core/Form/Select/SingleSelect/SingleSelect.test.tsx
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
  src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
Labels: enhancement

#858 [Feature] Details component
  .styleguidist/styleguidist.sections.js
  src/core/Details/Details.baseStyles.ts
  src/core/Details/Details.md
  src/core/Details/Details.test.tsx
  src/core/Details/Details.tsx
  src/core/Details/__snapshots__/Details.test.tsx.snap
  src/index.tsx
  src/reset/HtmlDetails/HtmlDetails.tsx
Labels: enhancement

#860 [Fix] TextInput examples
  src/core/Form/TextInput/TextInput.md
Labels: bug

#861 [Bugfix] SingleSelect input value in controlled state
  src/core/Form/Select/SingleSelect/SingleSelect.tsx
Labels: bug

#862 [Feature] FileInput
  .styleguidist/spacingprovider.md
  .styleguidist/styleguidist.sections.js
  package-lock.json
  package.json
  src/core/Form/Checkbox/Checkbox.tsx
  src/core/Form/DateInput/DatePicker/DateSelectors/DateSelectors.tsx
  src/core/Form/Dropdown/Dropdown/Dropdown.baseStyles.tsx
  src/core/Form/Dropdown/Dropdown/Dropdown.md
  src/core/Form/Dropdown/Dropdown/Dropdown.test.tsx
  src/core/Form/Dropdown/Dropdown/Dropdown.tsx
  src/core/Form/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/core/Form/Dropdown/DropdownItem/DropdownItem.basestyles.tsx
  src/core/Form/Dropdown/DropdownItem/DropdownItem.md
  src/core/Form/Dropdown/DropdownItem/DropdownItem.tsx
  src/core/Form/Dropdown/index.ts
  src/core/Form/FileInput/FileInput.baseStyles.tsx
  src/core/Form/FileInput/FileInput.md
  src/core/Form/FileInput/FileInput.test.tsx
  src/core/Form/FileInput/FileInput.tsx
  src/core/Form/FileInput/FileItem.tsx
  src/core/Form/FileInput/__snapshots__/FileInput.test.tsx.snap
  src/core/Form/index.ts
  src/core/theme/SpacingProvider/SpacingProvider.tsx
  src/core/theme/utils/spacing.ts
  src/index.tsx
  src/reset/HtmlInput/HtmlInput.tsx
Labels: new-component
