Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2024-09, with the labels that each got.

#871 [Fix] Update WizardNav docs
  src/core/Navigation/WizardNavigation/WizardNavigation/WizardNavigation.md
Labels: Documentation

#873 [Fix] Details varied content example accessibility
  src/core/Details/Details.md
Labels: Accessibility

#879 [Hotfix] Remove ExpanderContent animation
  package-lock.json
  package.json
  src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap
  src/core/Expander/ExpanderContent/ExpanderContent.baseStyles.tsx
  src/core/Expander/ExpanderContent/__snapshots__/ExpanderContent.test.tsx.snap
  src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
Labels: bug

#878 [Feature] RadioButtonGroup: Add groupStatus & groupStatusText
  src/core/Form/RadioButton/RadioButton.baseStyles.tsx
  src/core/Form/RadioButton/RadioButton.md
  src/core/Form/RadioButton/RadioButton.tsx
  src/core/Form/RadioButton/RadioButtonGroup.baseStyles.tsx
  src/core/Form/RadioButton/RadioButtonGroup.test.tsx
  src/core/Form/RadioButton/RadioButtonGroup.tsx
  src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
Labels: enhancement

#881 [Release] 15.0.0
  package.json
Labels: release
