Repository vrk-kpa/suomifi-ui-components, pull requests merged in 2024-08, with the labels that each got.

#867 [Fix] FileInput onChange
  src/core/Form/DateInput/DateInput.md
  src/core/Form/FileInput/FileInput.baseStyles.tsx
  src/core/Form/FileInput/FileInput.md
  src/core/Form/FileInput/FileInput.tsx
  src/core/Form/FileInput/__snapshots__/FileInput.test.tsx.snap
Labels: bug

#866 [Feature] React types update
  package-lock.json
  package.json
  src/core/Form/SearchInput/SearchInput.tsx
  src/core/Form/Select/BaseSelect/SelectEmptyItem/SelectEmptyItem.tsx
  src/core/Pagination/PageInput/PageInput.tsx
  src/core/utils/Debounce/Debounce.tsx
Labels: dependencies

#868 [Release] 15.0.0-beta.1
  package.json
Labels: release

#870 [Release] 15.0.0-beta.2
  package.json
Labels: release
